### ISSUE TITLE
[TRI-2208] Bulk import environment variables (v3)

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#1016]
The ability to copy+paste a load of environment variables at once.

Important considerations
- We have multiple environments, so you'll want to select an environment (or possibly multiple? Possibly a bit weird given they're normally different across environments).
- What should we do if there's an existing env var in that environment with the same key? Just override? Or possibly it should have a red warning next to it so you can choose to remove it before you confirm?

<sub>[TRI-2208](https://linear.app/triggerdotdev/issue/TRI-2208/bulk-import-environment-variables-v3)</sub>

**Comment by pkpio** [comment]
I think vercel's approach should work well enough. Each time you are adding a variable(s), you have the choice of selecting environments to import to. 

If a variable already exists in an environment, it refuses to import.

**Comment by manurana** [comment]
Maybe also a CLI util (a la SST.dev)
- import from a file (option of json/env)
- export to a file

**Comment by matt-aitken** [comment]
We now have bulk import in the UI, SDK functions, and the ability to sync them in your trigger.config file. Docs here: https://trigger.dev/docs/v3/deploy-environment-variables
