### ISSUE TITLE
bug: v3 CLI Error: Span processor did not completed within timeout period

### ISSUE THREAD

**Issue by ky-zo** [triggerdotdev/trigger.dev#1159]
### Provide environment information

 System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 169.73 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.5.2 - ~/myproject/node_modules/.bin/npm

### Describe the bug

The v3 project creator said the project was initialized successfully, and then threw error asking me to open issue on github.

`●     3. Head over to our v3 docs (​https://trigger.dev/docs/v3​) to learn more.
│
●     4. Need help? Join our Discord community (​https://trigger.dev/discord​) or email us at help@trigger.dev
│
└  Project initialized successfully. Happy coding!

✘ [ERROR] An unknown error has occurred. Please open an issue on github with the below:

✘ [ERROR] [

    Error: Span processor did not completed within timeout period of 500 ms
        at Timeout._onTimeout
  (/Users/kamil/.npm/_npx/615bebf0b780b73f/node_modules/@opentelemetry/sdk-trace-base/build/src/BasicTracerProvider.js:109:29)
        at listOnTimeout (node:internal/timers:573:17)
        at process.processTimers (node:internal/timers:514:7)
  ]
`

### Reproduction repo

n/a

### To reproduce

Run the CLI again?

### Additional information

I already had the V2 Project set up in my codebase, it's possible that this somehow interfered with the v3.

**Comment by nicktrn** [comment]
Hey @ky-zo, thanks for creating an issue. This is due to a timeout that's a bit too aggressive. Luckily, we fixed this a few days ago in c11a77f50b9207b5fa83053ec7b7b0beb45f5498 but new packages are yet to be released. We're in the process of running some tests on the latest changes and should release a new CLI within the next day or two.

**Comment by ky-zo** [comment]
cool, thanks!

**Comment by matt-aitken** [comment]
Ok I think this was fixed in `3.0.0-beta.37`
