### ISSUE TITLE
"View logs" CLI links sometimes don't work when clicked

### ISSUE THREAD

**Issue by ky-zo** [triggerdotdev/trigger.dev#1160]
### Provide environment information

N/A

### Describe the bug

<img width="595" alt="Screenshot 2024-06-11 at 23 41 08" src="https://github.com/triggerdotdev/trigger.dev/assets/30871809/69c9ebbc-fff6-4443-8536-faefb45d3b0b">

After a task run, the terminal suggests going into a link:
https://cloud.trigger.dev/projects/v3/proj_id/runs/run_id​)

this doesn't work, as link must have the org info too:

https://cloud.trigger.dev/orgs/org_name/projects/v3/proj_id/runs/run_id​the 

### Reproduction repo

N/A

### To reproduce

N/A

**Comment by matt-aitken** [comment]
We use this [very popular package](https://github.com/sindresorhus/terminal-link) for links – it automatically renders them in brackets like this if your terminal doesn't support links.

When it's falling back like this, sometimes the links wraps over multiple lines or in other situations VSCode doesn't interpret them correctly. 

I'm going to leave this issue open but I'm not sure what a good fix for this is.

**Comment by nicktrn** [comment]
Would be good to collect some information on the environments this happens in, maybe we could detect it and render the links differently in those cases.

@ky-zo
- What OS are you on?
- You're running this in VSCode, what's your default terminal set to? You can check like this:
![image](https://github.com/triggerdotdev/trigger.dev/assets/55853254/dedbedd5-69c5-459d-8cf5-940209c54c2b)
- Are you running VSCode, your terminal, or anything else with sudo?
- Maybe you could also send us your env vars by doing a 'printenv` in the terminal this happens in and censor some bits.
