### ISSUE TITLE
Gmail events

### ISSUE THREAD

**Issue by tonyxiao** [triggerdotdev/trigger.dev#121]
Loving everything about trigger.dev so far! Only issue is that there are triggers from Zapier / Pipedream that I really rather not redo myself. Notably gmail new message / new labeled email events. Is there a roadmap for integrations?

**Comment by ericallam** [comment]
Hey @tonyxiao, thanks! We're working hard currently to build a revamped trigger.dev that will lead to much improved integration velocity (you can read more about our plans on our blog [here](https://blog.trigger.dev/posts/trigger-q2-2023-plans)).

**Comment by ericallam** [comment]
Hey @tonyxiao, I'm closing this issue for now but please re-open it if you still want this feature.
