### ISSUE TITLE
feat: Allow injecting ca cert in project

### ISSUE THREAD

**Issue by gautamsi** [triggerdotdev/trigger.dev#1210]
### Is your feature request related to a problem? Please describe.

I was playing with the self-hosted deployment in an isolated environment with a private registry. Found out that it fails to even build due to private certification authority. 

Build works without problem but can not be run as the entrypoint tries to connect to self hosted trigger.dev api which is secured by self signed/private cert chain.

Allowing to inject private root cert which will allow securely interacting with the internal services would be helpful.

### Describe the solution you'd like to see

A config option to include a ca file which would then be added to `NODE_EXTRA_CA_CERTS=/app/ca.crt` environment variable during docker build and worker initialization.

### Describe alternate solutions

Allow replacing `Containerfile.prod` along with build/runtime variable using config instead of through the project setting. project settings can not even be fetched in this scenario

### Additional information

For others who want to be able to do this in current scenario (tested beta-48), do this

1. install `trigger.dev@beta` as dev dependency instead of running from npx, 

2. add `ca.crt` file in your project and update config `additionalFiles: ["./ca.crt"]` to copy this.

3. in file `node_modules\trigger.dev\dist\Containerfile.prod` update the section for ENV with following
```yaml
ENV TRIGGER_PROJECT_ID=${TRIGGER_PROJECT_ID} \
    # ... ....
    NODE_ENV=production \
    NODE_EXTRA_CA_CERTS=/app/lib/ca.crt # this line
```

4. Update `node_modules\trigger.dev\dist\workers\prod\entry-point.js`, update function `gatherProcessEnv` at the very end of file like this
```js
function gatherProcessEnv() {
  const env = {

    NODE_ENV: process.env.NODE_ENV ?? "production",
// ... other config
    NODE_EXTRA_CA_CERTS: process.env.NODE_EXTRA_CA_CERTS, //// THIS LINE
  };
  return Object.fromEntries(Object.entries(env).filter(([key, value]) => value !== void 0));
}
```

step 3 and 4 needs to be done inside `node_modules`, this can be patched with `patch-packages` or `yarn patch`.  caveat is that as of writing this issue, the library is getting updated almost every day.

I can definitely create a pull request over next few days which should fix this if acceptable.

**Comment by nicktrn** [comment]
Thanks for reporting this @gautamsi. That's definitely a valid use-case we should support. Did you try setting the env var via the dashboard and enabling it for prod? I think that should work.

**Comment by gautamsi** [comment]
@nicktrn setting prod variable does not work (I assumed so but still verified)
reason is that my registry as well as trigger.dev deployment is protected using self signed cert. 

cli works as the cert is enabled on my system and right env variable, docker containers and ca cert is also injected to all trigger docker container using compose override.
but the container spun for running tasks does not have a way to inject a variable and volume

**Comment by nicktrn** [comment]
Okay, so we indeed have to set this before launching the entrypoint. Makes sense, as the step that fetches the env vars from the platform won't know about the extra certs.

A new config option would probably be the correct place to put this, maybe `extraCaCerts`. It would prevent having to set things in two places. PR would be great if you get a chance :pray:

**Comment by gautamsi** [comment]
@nicktrn This is two fold problem, 
1. We can not set NODE_EXTRA_CA_CERTS value at runtime, this means it has to be built in to the image using `Containerfile.prod`
2. This have to be available to the worker, this means we have to set this in `gatherProcessEnv()` to pass on to the actual task worker process.

I am going to try to update the file based on my finding and create PR over weekend
