### ISSUE TITLE
can't deploy anymore using `npx trigger.dev@beta deploy`

### ISSUE THREAD

**Issue by joelbqz** [triggerdotdev/trigger.dev#1282]
### Provide environment information

  System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 82.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.nvm/versions/node/v21.7.3/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v21.7.3/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.3/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v21.7.3/bin/pnpm
    bun: 1.1.18 - ~/.bun/bin/bun

### Describe the bug

This was working yesterday on my computer but today I'm receiving this error 
<img width="566" alt="image" src="https://github.com/user-attachments/assets/ec568cfa-50ca-421c-aa14-d493c5a06ddd">

It's also not working with Github Actions

### Reproduction repo

no repo

### To reproduce

run `npx trigger.dev@beta deploy`

**Comment by matt-aitken** [comment]
Hi @joelbqz,
There's been a change in one of those downstream packages that's started to cause this.

You can use our new build system which is preview but will become main next week: https://trigger.dev/docs/guides/new-build-system-preview
