### ISSUE TITLE
doc need: creating a new reference project and deploying it locally

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#1362]
We're missing a doc in the repo (ideally at `references/README.md`) that details how to:

- Create a new reference project by copying the `hello-world` reference project
- Get the dev CLI command running against a local instance of Trigger.dev (e.g. the webapp)
- Get the deploy CLI command running against a local instance of Trigger.dev by setting up and running the webapp alongside the coordinator and docker-provider:

```sh
pnpm run dev --filter webapp --filter coordinator --filter docker-provider
```

Then deploying it like so:

```sh
pnpm exec trigger deploy --self-hosted --load-image
```

This README should also make sure the CONTRIBUTING.md guidelines are enough to get the webapp running locally.

This new README should be sufficient for a new contributor to come in from scratch and create a new reference project and both run it in dev and deploy it.

**Comment by neo773** [comment]
@ericallam 
Wouldn't it be better to use the CLI's init command instead of copying over the `hello-world` project? as it creates the same files

**Comment by ericallam** [comment]
@varshith257 I can't remember how to assign things with Algora or if that's even possible, but here is a gif instead:

![bart-simpson-episode-20-gif](https://github.com/user-attachments/assets/d39c9702-704a-4e3c-97c4-e1c3ac862702)

**Comment by Kritik-J** [comment]
@ericallam I would like to work on it, Can I get it assigned?

**Comment by ericallam** [comment]
I've been informed that GitHub has issue assignment built in, and gifs don't count. So I've assigned @varshith257 (and myself), to this issue. @Kritik-J thanks for the offer, but since @varshith257 came first I'll give them a crack at it 🫡

**Comment by ericallam** [comment]
@varshith257 any updates?

**Comment by varshith257** [comment]
@ericallam Will draft PR soon

**Comment by lostinvsc** [comment]
He is taking too much time

**Comment by ericallam** [comment]
@Wackyator how are things going with this issue? Anything I can help with?

**Comment by Wackyator** [comment]
@ericallam I've mentioned something in the discord thread that I require some help on, I've created a draft PR for the time being.
