### ISSUE TITLE
[TRI-3840] Logging infinitely recursive javascript objects crashes, inside flattenAttributes.

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#1431]
## Problem

If you try and log an object that has a circular reference, our `flattenAttributes` code will exceed the stack depth and fail. 

Example: a user that has blog posts that have an author (that points back at the user).

This is a major issue with MongoDB which returns JS objects like this.

## Solution
Detect circular objects and don't add them to the log output, put a placeholder string instead.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-3840](https://linear.app/triggerdotdev/issue/TRI-3840/logging-infinitely-recursive-javascript-objects-crashes-inside)</sub>

**Comment by yadavshubham01** [comment]
hey @matt-aitken solve this issue please checkout this PR #1433
