### ISSUE TITLE
bug: SDK typings broken on v3.1.0

### ISSUE THREAD

**Issue by marbemac** [triggerdotdev/trigger.dev#1440]
### Provide environment information

  System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 415.19 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.0.0 - ~/.nvm/versions/node/v22.0.0/bin/node
    Yarn: 4.5.0 - ~/.nvm/versions/node/v22.0.0/bin/yarn
    npm: 10.5.1 - ~/.nvm/versions/node/v22.0.0/bin/npm
    bun: 1.1.29 - ~/.bun/bin/bun

### Describe the bug

Typings are broken on the 3.1.0 SDK release. Working on 3.0.13.

<img width="762" alt="Screenshot 2024-10-30 at 12 42 07 PM" src="https://github.com/user-attachments/assets/9f72b947-0714-4944-8365-b014f3ab7330">

### Reproduction repo

...

### To reproduce

Install 3.1.0. In case it matters, I've got `"type": "module",` in my `package.json` file.

**Comment by ericallam** [comment]
What's your tsconfig.json?

**Comment by marbemac** [comment]
🤦‍♂️  we've got `"customConditions": ["workerd", "worker", "browser"]` in there because historically we've mostly working in cloudflare environments. That was the issue - feel free to close. Thanks!

**Comment by ericallam** [comment]
This has been fixed in 3.1.1
