### ISSUE TITLE
Issue on docs: useRealtime Batch does not exist.

### ISSUE THREAD

**Issue by Pape98** [triggerdotdev/trigger.dev#1446]
Path: /frontend/react-hooks 

I kept getting the following error when trying to import the function:

```The requested module '@trigger.dev/react-hooks' does not provide an export named 'useRealtimeBatch```. It's because the actual hook function in the library is defined as `useBatch` and not `useRealtimeBatch`.

**Comment by ericallam** [comment]
This has been fixed in 3.1.1
