### ISSUE TITLE
Error with setup "pnpm dlx @trigger.dev/cli@latest init" vs. "npx @trigger.dev/cli@latest init -k tr_dev_*********** -t https://cloud.trigger.dev"

### ISSUE THREAD

**Issue by owen-duncan-snobel** [triggerdotdev/trigger.dev#145]
I was having a problem with setting up the initial init. I was following the tutorial from the jobs page and when I copy and paste the string with the params included from step 1 it fails. (See fig 1. and fig.2)

```Aborting installation...
TypeError [ERR_INVALID_URL]: Invalid URL
 ERROR  Command failed with exit code 1: cli init -k tr_dev_***********  -t https://cloud.trigger.dev

pnpm: Command failed with exit code 1: cli init -k tr_dev_*********** -t https://cloud.trigger.dev
    at makeError (/opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:24241:17)
    at handlePromise (/opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:24812:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (/opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:207055:7)
    at async /opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:216461:21
    at async main (/opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:216428:34)
    at async runPnpm (/opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:216683:5)
    at async /opt/homebrew/Cellar/pnpm/8.6.2/libexec/dist/pnpm.cjs:216675:7
```

<img width="731" alt="Screenshot 2023-07-07 at 3 15 50 PM" src="https://github.com/triggerdotdev/trigger.dev/assets/43126781/fdd8a368-b5e0-46eb-ada2-4d6bf1cb2cf5"> fig 1.

<img width="661" alt="Screenshot 2023-07-07 at 3 14 02 PM" src="https://github.com/triggerdotdev/trigger.dev/assets/43126781/74f2acfa-2d72-4432-96dd-119af1fb9c3b"> fig 2.

But if I follow the guide from https://trigger.dev/docs/documentation/quickstart and I don't pass the params and use the command line it works. (See fig 3.)

Works: ```pnpm dlx @trigger.dev/cli@latest init```
Does not work:  ```pnpm dlx @trigger.dev/cli@latest init -k tr_dev_********** -t https://cloud.trigger.dev```

<img width="701" alt="Screenshot 2023-07-07 at 3 16 25 PM" src="https://github.com/triggerdotdev/trigger.dev/assets/43126781/50516275-d7c2-4c47-a342-6050c16e1fbf">

**Comment by ericallam** [comment]
Thanks for reporting this and for all the details you've included! Should make it easy enough to track down 👍

**Comment by matt-aitken** [comment]
@owen-duncan-snobel this issue is now fixed
