### ISSUE TITLE
[TRI-4146] Realtime: some run errors aren't parsed correctly

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#1532]
Run errors which don't have a `message` fail to parse and cause errors on the frontend:

This error happens when a run is cancelled:
```json
"error": "{\"raw\": \"Task run was cancelled by user\", \"type\": \"STRING_ERROR\"}",
```

It results in this error (from Zod)
![image](https://github.com/user-attachments/assets/c46f485f-75fd-4312-8e82-f7503c6de911)

<sub>[TRI-4146](https://linear.app/triggerdotdev/issue/TRI-4146/realtime-some-run-errors-arent-parsed-correctly)</sub>

**Comment by ericallam** [comment]
This has been fixed in 3.3.5
