### ISSUE TITLE
Bug: useRealtimeRun continues fetching run data after completion in v3.3.5

### ISSUE THREAD

**Issue by EnriqueSantos-dev** [triggerdotdev/trigger.dev#1538]
### Provide environment information

  System:
    OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 7700 8-Core Processor
    Memory: 11.72 GB / 15.20 GB
    Container: Yes
    Shell: 3.7.0 - /usr/bin/fish
  Binaries:
    Node: 20.17.0 - ~/.local/share/nvm/v20.17.0/bin/node
    npm: 10.8.2 - ~/.local/share/nvm/v20.17.0/bin/npm
    pnpm: 9.10.0 - ~/.local/share/nvm/v20.17.0/bin/pnpm

### Describe the bug

The `useRealtimeRun` hook keeps making requests even after the run has been completed, causing unnecessary network load.

### Reproduction repo

https://github.com/EnriqueSantos-dev/nextjs-realtime-simple-demo

### To reproduce

1. Copy the contents of `.env.local.example`, paste them into a new `.env` file, and populate it with your environment variables.  
2. Update the placeholder project reference in the `trigger.config.ts` file.

### Additional information

https://github.com/user-attachments/assets/e9b181dc-4ccf-4b26-ae06-c21b8289f17c

**Comment by ericallam** [comment]
Thanks for the report, will be digging into this on Monday!
