### ISSUE TITLE
[TRI-644] On a Run retry add info to `context.run`

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#154]
When this button is pressed it retries the existing run.

![Linear-hosted image](https://github.com/triggerdotdev/trigger.dev/assets/10635986/8e7abfb8-a962-42a2-9387-30796b3142b5)
[Image source](https://github.com/triggerdotdev/trigger.dev/assets/10635986/8e7abfb8-a962-42a2-9387-30796b3142b5)

In this case, we should add some metadata to `context.run` so you can identify that it is a rerun and potentially how many attempts have been made as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-644](https://linear.app/triggerdotdev/issue/TRI-644/on-a-run-retry-add-info-to-contextrun)</sub>

**Comment by ericallam** [comment]
I think initially we should just add an `isRetry` boolean in the `context.run` object

**Comment by akhill10** [comment]
/attempt #154

New to this repo. Seems like a good issue to start contributing. I will take this up 😃 

@ericallam  If I understand it correctly, when it retries the existing run, it creates an eventLog ( EventRecord ) with the context same as existing run context. We just need to add an `isRetry` boolean to this context right?
