### ISSUE TITLE
bug: Prisma prismaSchemaFolder  extension causes trigger.dev deploy to fail

### ISSUE THREAD

**Issue by RobertHH-IS** [triggerdotdev/trigger.dev#1565]
### Provide environment information

NextJS 14.2
@prisma/client@6.0.1
@trigger.dev/sdk": "3.3.7

### Describe the bug

the build also fails if using prismaSchemaFolder extension.  

If schema.prisma
`generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["postgresqlExtensions", "prismaSchemaFolder", "fullTextSearchPostgres"]
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}
`

And then you create other.prisma and user.prisma.. everything works fine in NextJS.. however trigger.dev build says that schema.prisma is empty and errors out.

If all models are thrown into schema.prisma it works.

Tried including additional files in 
import { defineConfig } from '@trigger.dev/sdk/v3';
import {
   additionalPackages,
   additionalFiles,
} from '@trigger.dev/build/extensions/core';
import { prismaExtension } from '@trigger.dev/build/extensions/prisma';

   build: {
      extensions: [
         additionalFiles({
            files: ['./prisma/schema/**'],
         }),
         prismaExtension({
            schema: 'prisma/schema.prisma',
            clientGenerator: 'client',
         }),
         additionalPackages({
            packages: ['@prisma/client@6.0.1'],
         }),
      ],
   },

### Reproduction repo

None

### To reproduce

Set up prisma in nextjs with prismaSchemaFolder extension.
Create schema.prisma with no schemas
`generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["prismaSchemaFolder"]
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}
`
Create user.prisma with schemas

`model User {
    id               String                    @id @unique
    email            String                    @unique
    name             String?

    @@index([email])
}`

Set up trigger.config.ts
import { defineConfig } from '@trigger.dev/sdk/v3';
import {
   additionalPackages,
   additionalFiles,
} from '@trigger.dev/build/extensions/core';
import { prismaExtension } from '@trigger.dev/build/extensions/prisma';

   build: {
      extensions: [
         additionalFiles({
            files: ['./prisma/schema/**'],
         }),
         prismaExtension({
            schema: 'prisma/schema.prisma',
            clientGenerator: 'client',
         }),
         additionalPackages({
            packages: ['@prisma/client@6.0.1'],
         }),
      ],
   },

Trigger.dev fails to deploy.  With or without additionalFiles.  It does not seem to load in the extension.
Error is simply that there are no models in the schema.prisma

If all models are thrown into schema.prisma it works.

**Comment by ericallam** [comment]
@RobertHH-IS This definitely should work, and I haven't been able to replicate this. Do you think you could publish an actual repo on GitHub that reproduces this issue? That would be extremely helpful if so 🫡

**Comment by RobertHH-IS** [comment]
Certainly:
https://github.com/RobertHH-IS/trigger-prismafolder

when following the step 
pnpm dlx trigger.dev@latest deploy

I get error 
#18 0.675 Prisma schema loaded from prisma/schema/schema.prisma
#18 0.768 Error:
#18 0.768 You don't have any models defined in your schema.prisma, so nothing will be generated.
#18 0.768 You can define a model like this:
#18 0.768
#18 0.768 model User {
#18 0.768   id    Int     @id @default(autoincrement())
#18 0.768   email String  @unique
#18 0.768   name  String?
#18 0.768 }
#18 0.768
#18 0.768 More information in our documentation:
#18 0.768 https://pris.ly/d/prisma-schema
#18 0.768
#18 ERROR: process "/bin/sh -c node node_modules/prisma/build/index.js generate" did not complete successfully: exit code: 1
------

i tried it with and without the additionalFiles extension

**Comment by ericallam** [comment]
@RobertHH-IS thanks for the reproduction, I've been able to track down what is going on here. Apparently when using the `prismaSchemaFolder` preview feature, you have to switch to no longer passing the schema **file** to CLI commands, and update it to passing the schema **dir**:

![CleanShot 2024-12-15 at 21 22 31@2x](https://github.com/user-attachments/assets/30ed9920-2178-4ec2-94ae-59c9897efab5)

In the package.json of this project you are actually doing that correctly, but the prisma CLI will actually use the setting in the package.json if it exists (and the `--schema` flag isn't passed into the prisma CLI command):

![CleanShot 2024-12-15 at 21 23 07@2x](https://github.com/user-attachments/assets/55649bf9-1439-457b-a808-ee5e724462fb)

The `trigger.dev deploy` command was copying that prisma configuration from your package.json to the container, but it wasn't passing a `--schema` flag to the `generate` command pointing to the schema **dir**. We could fix this on our end by making sure that `--schema` flag is always passed, but in the meantime, simply changing the package.json to this will fix the problem:

![CleanShot 2024-12-15 at 21 25 29@2x](https://github.com/user-attachments/assets/c8a25a42-1286-41d8-ad62-fd82ef62e43b)

Also, there's no need to use the `additionalFiles` extension, as we will already detect using multiple .prisma files and copy them into the deployed image.

**Comment by RobertHH-IS** [comment]
Correct - working now :-)
Thanks!
