### ISSUE TITLE
[TRI-321] Better handle errors bubbling up in subtasks

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#159]
Currently when viewing a failed task because a subtasks threw an error is not a great experience. We need to improve that

When a subtask fails (and all retries are done) the error doesn't bubble up to the parent task. Instead you get a very generic: "Error: Task errored at IO.runTask".

Instead, a failed subtask should bubble that error up to parent tasks (so the subtask error is duplicated onto the parent).

You can easily reproduce this by creating a task with subtask inside that throws a specific error.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-321](https://linear.app/triggerdotdev/issue/TRI-321/better-handle-errors-bubbling-up-in-subtasks)</sub>

**Comment by SSHari** [comment]
@ericallam would it be possible to get more information about what the bad experience is and what the expected experience should be?

**Comment by rishi-raj-jain** [comment]
@ericallam Can I work on this one? Can you elaborate the issue?

**Comment by rishi-raj-jain** [comment]
@ericallam would it be possible to get more information about what the bad experience is and what the expected experience should be?

**Comment by rishi-raj-jain** [comment]
@matt-aitken @ericallam

Would it be possible to get more information about what the bad experience is and what the expected experience should be?

**Comment by matt-aitken** [comment]
I've added more information to the original issue

**Comment by matt-aitken** [comment]
@RamK777-stack would you like to claim the Algora bounty?

**Comment by RamK777-stack** [comment]
Yes @matt-aitken

**Comment by RamK777-stack** [comment]
claim #159

**Comment by matt-aitken** [comment]
This was fixed
