### ISSUE TITLE
[TRI-445] Update Docker image to follow Node.js Docker guidelines

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#160]
[https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/](https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/)

We need to go through this entire post and make sure we are following their suggestion in our Dockerfile, specifically these are most relevant:

* Use explicit and deterministic Docker base image tags
* Don’t run containers as root
* Safely terminate Node.js Docker web applications
* Graceful shutdown for your Node.js web applications
* Keeping unnecessary files out of the image

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-445](https://linear.app/triggerdotdev/issue/TRI-445/update-docker-image-to-follow-nodejs-docker-guidelines)</sub>

**Comment by harshbisle** [comment]
`/attempt #160`

**Comment by puru-khedre** [comment]
/ attempt #160
