### ISSUE TITLE
[TRI-583] CLI Init: If there's an endpoint ID in package.json, use it

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#165]
<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-583](https://linear.app/triggerdotdev/issue/TRI-583/cli-init-if-theres-an-endpoint-id-in-packagejson-use-it)</sub>

**Comment by rishi-raj-jain** [comment]
I believe this can be closed now?
