### ISSUE TITLE
[TRI-654] Add an `update` sub-command the @trigger.dev/cli that updates all @trigger.dev/* packages

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#166]
It's annoying currently updated `@trigger.dev/*` packages to the latest ones so we should have a command that could be run like so:

```
$ npx @trigger.dev/cli update
```

This should find all the `@trigger.dev/*` packages in the package.json of the current project and use the NPM registry API to figure out if there are newer versions. It should display which ones are newer and ask for confirmation before updating the package.json and re-installing dependencies.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-654](https://linear.app/triggerdotdev/issue/TRI-654/add-an-update-sub-command-the-triggerdevcli-that-updates-all)</sub>

**Comment by zodman** [comment]
/attempt #166

what about integrate the npm-check-updates like a dependency ?

**Comment by rishi-raj-jain** [comment]
@ericallam Can I work on this one?
