### ISSUE TITLE
[TRI-655] The `@trigger.dev/cli dev` command should detect out-of-date packages

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#167]
It should check the npm registry for any of the `@trigger.dev/*` packages in the current project and output a warning, and also mention the `update` command (#166)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-655](https://linear.app/triggerdotdev/issue/TRI-655/the-triggerdevcli-dev-command-should-detect-out-of-date-packages)</sub>

**Comment by rishi-raj-jain** [comment]
@ericallam Can I work on this one?

**Comment by neo773** [comment]
@ericallam Can we close this?
