### ISSUE TITLE
[TRI-660] Add steps to the contributing guide on getting some jobs running locally

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#172]
It would be really helpful I think to include very explicit instructions for how to get some example jobs running locally for contributors to this project. Currently we have the `nextjs-example` example inside the repo but it's got WAY too many jobs in it to be useful, especially for first time contributors.

So part of this issue would be to create a barebones nextjs example (maybe something called `examples/jobs-starter` or similar) that just has a few simple (scheduled and event triggers) jobs and then add instructions to the contributing guide for getting those into the local instance and running them

<sub>[TRI-660](https://linear.app/triggerdotdev/issue/TRI-660/add-steps-to-the-contributing-guide-on-getting-some-jobs-running)</sub>

**Comment by tobihans** [comment]
I'd like to /attempt #172 this.
