### ISSUE TITLE
[TRI-661] We need to add instructions in CONTRIBUTING.md for adding changesets to PRs

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#178]
null

<sub>[TRI-661](https://linear.app/triggerdotdev/issue/TRI-661/we-need-to-add-instructions-in-contributingmd-for-adding-changesets-to)</sub>

**Comment by kaf-lamed-beyt** [comment]
Since I just learned how to add a changeset. I'd love to do this @ericallam

**Comment by kaf-lamed-beyt** [comment]
Hi @ericallam, I'm waiting for your review on #200 so I can fix it before starting this, to avoid having the commits from that branch in this one when I start working on it.
