### ISSUE TITLE
[TRI-662] Add instructions to the CONTRIBUTING.md file for adding and running migrations

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#179]
null

<sub>[TRI-662](https://linear.app/triggerdotdev/issue/TRI-662/add-instructions-to-the-contributingmd-file-for-adding-and-running)</sub>

**Comment by kaf-lamed-beyt** [comment]
Hi @ericallam,

If you can give me a brief info about this issue, perhaps, on what needs to be done, I'd love to work on it.
