### ISSUE TITLE
[TRI-701] Add job count pill to the Project drop down in breadcrumb

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#192]
Add the same job count pill found in the Organization list

<img width="491" alt="CleanShot 2023-07-19 at 22 17 57@2x" src="https://github.com/triggerdotdev/trigger.dev/assets/534/0bf3a825-2b2e-41f4-8969-c8b25843519c">

To the Project selector dropdown in the breadcrumbs:

<img width="377" alt="CleanShot 2023-07-19 at 22 18 16@2x" src="https://github.com/triggerdotdev/trigger.dev/assets/534/a060a8b5-353c-4ea9-a3c7-ad3f4f259dad">

<sub>[TRI-701](https://linear.app/triggerdotdev/issue/TRI-701/add-job-count-pill-to-the-project-drop-down-in-breadcrumb)</sub>

**Comment by SSHari** [comment]
/attempt https://github.com/triggerdotdev/trigger.dev/issues/192
