### ISSUE TITLE
[TRI-703] Chore: update webapp to Remix 2.0.1

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#198]
We're already using most of Remix's v2 features, as future flags in our [remix.config.js](https://github.com/triggerdotdev/trigger.dev/blob/e350659e244e6976747f726984c83a780ba94882/apps/webapp/remix.config.js#L3).

## How to

1. Read Remix's recommendations in the [v2 release](https://github.com/remix-run/remix/releases/tag/remix%402.0.0)
2. They recommend upgrading to 1.19.3 first: `npx upgrade-remix 1.19.3`.
3. Upgrading to `v2_meta` and `v2_headers`. These should be trivial as I don't think we use the headers function anywhere, and every route on the site requires login so only the root.tsx meta function is being used right now.
4. Upgrade Remix to [v2.0.1](https://github.com/remix-run/remix/releases/tag/remix%402.0.1).
5. Run `pnpm run typecheck --filter webapp` to find and fix TypeScript errors.
6. Run the webapp and check it functions as expected

Please follow the [contribution guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md) development section to setup and run the web app.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-703](https://linear.app/triggerdotdev/issue/TRI-703/chore-update-webapp-to-remix-201)</sub>

**Comment by Rutam21** [comment]
I would love to work on this. Please assign this to me. Thanks!

CC: @ericallam @matt-aitken

**Comment by nicktrn** [comment]
Completed in c0f9f10b075f479f1d1429f6302cefc370a76510
