### ISSUE TITLE
[TRI-709] Add git database tasks to `@trigger.dev/github` integration

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#201]
The `@trigger.dev/github` integration currently only supports a limited number of tasks found here:

https://github.com/triggerdotdev/trigger.dev/blob/main/integrations/github/src/tasks.ts

We should add tasks for cover the entire "git database" collection of rest API endpoints, found here:

- [ ] Blobs: https://docs.github.com/en/rest/git/blobs?apiVersion=2022-11-28
- [ ] Commits: https://docs.github.com/en/rest/git/commits?apiVersion=2022-11-28
- [ ] References: https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28
- [ ] Tags: https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28
- [ ] Trees: https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28

<sub>[TRI-709](https://linear.app/triggerdotdev/issue/TRI-709/add-git-database-tasks-to-triggerdevgithub-integration)</sub>

**Comment by matt-aitken** [comment]
There's a GitHub Job file you can use when testing:
https://github.com/triggerdotdev/trigger.dev/blob/main/examples/nextjs-example/src/jobs/github.ts

**Comment by akhill10** [comment]
I m taking this up 😃 
/attempt #201
