### ISSUE TITLE
[TRI-710] Create an initial end-to-end test harness

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#202]
We need to add an automated test suite that does end-to-end testing of the entire system. This issue covers creating an initial test harness that should do the following things:

- Run the Trigger.dev webapp backed by a fresh Postgres database using docker (maybe using the [dev-compose.yml](./docker/dev-compose.yml) file using `pnpm run dev:docker`)
- Using something like Playwright, create an account
- Retrieve a dev API key
- Use the API key in a test Next.js project that already includes some testing jobs
- Run the Next.js project and the `@trigger.dev/cli dev` command to connect to the running Trigger.dev webapp
- Using playwright, navigate to the jobs list and make sure the correct jobs have been created
- Stop the docker services running

This should all happen in some kind of test runner (maybe vitest?) that should be able to be run using the `pnpm run test:e2e` command. This should also be added to the github publish workflow. 

<sub>[TRI-710](https://linear.app/triggerdotdev/issue/TRI-710/create-an-initial-end-to-end-test-harness)</sub>

**Comment by ericallam** [comment]
@Ashutosh-Bhadauriya how's this coming along, need help with anything?

**Comment by Ashutosh-Bhadauriya** [comment]
Hi Eric, started it today. There are still some things I need to figure out, will reach out if any help is needed.

**Comment by zodman** [comment]
im step down ...
