### ISSUE TITLE
[TRI-711] Add JavaScript support to the CLI init command

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#205]
Currently the init command generates TypeScript files:

* trigger.ts
* The API route (location and content varies for pages or app router)
* Example job file

If JavaScript is detected then we should generate JS files instead of TS.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-711](https://linear.app/triggerdotdev/issue/TRI-711/add-javascript-support-to-the-cli-init-command)</sub>

**Comment by ericallam** [comment]
The init command already detects if the Next.js project is using TS, so we should just use that instead of prompting

**Comment by jemiluv8** [comment]
/attempt #205

Seems interesting.
