### ISSUE TITLE
[TRI-732] Replace `tsconfig` package with `tsconfck` in @trigger.dev/cli

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#211]
Currently we are using the [tsconfig](https://www.npmjs.com/package/tsconfig) package for parsing/resolving the tsconfig.json file, but unfortunately the tsconfig package does not support trailing commas (see [here](https://github.com/TypeStrong/tsconfig/issues/30)) (which tsconfig.json does for some reason). We should replace the tsconfig package with [tsconfck](https://www.npmjs.com/package/tsconfck) to better support the weird dialect of JSON that is tsconfig.json.

<sub>[TRI-732](https://linear.app/triggerdotdev/issue/TRI-732/replace-tsconfig-package-with-tsconfck-in-triggerdevcli)</sub>

**Comment by SSHari** [comment]
/attempt https://github.com/triggerdotdev/trigger.dev/issues/211
