### ISSUE TITLE
[TRI-768] The CLI init command should generate a jobs/index file and jobs should be imported there.

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#224]
When `npx @trigger.dev/cli@latest init` is run it generates the Trigger API route, and an example job.

In the Trigger API route (`app/api/trigger.route.ts` for app router and `pages/api/trigger.ts` for pages router) it imports an individual example job:

```
import { createAppRoute } from "@trigger.dev/nextjs";
import { client } from "@/trigger";

// Replace this with your own jobs
import "@/jobs/examples";

//this route is used to send and receive data with Trigger.dev
export const { POST, dynamic } = createAppRoute(client);
```

Let's change it so we have an `index` file inside the `jobs` folder and just that is imported here.

In that `index` file we would import the `examples` file.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-768](https://linear.app/triggerdotdev/issue/TRI-768/the-cli-init-command-should-generate-a-jobsindex-file-and-jobs-should)</sub>

**Comment by jemiluv8** [comment]
I've started it by the way.

**Comment by wwzeng1** [comment]
/attempt #224, I'm using Sweep (AI junior developer) to try this issue https://github.com/sweepai/sweep#getting-started-

**Comment by jemiluv8** [comment]
@wwzeng1 your sweep projects looks awesome.
This issue is really the kind that it should be able to do.
I'm looking forward to see what it comes up with

**Comment by wwzeng1** [comment]
Thanks @jemiluv8! I'm trying to prompt it correctly right now

**Comment by matt-aitken** [comment]
@wwzeng1 I was looking at Sweep the other day, it looks really cool. Congrats on YC, we're W23.

**Comment by wwzeng1** [comment]
@matt-aitken Thanks Matt! Sorry I’m not familiar with typescript, but I think if a more experienced dev prompted Sweep for your repo it would go well! This is our install link: https://github.com/apps/sweep-ai

**Comment by rishi-raj-jain** [comment]
@matt-aitken

Can I work on this one?
