### ISSUE TITLE
[TRI-879] Conditionally hide the help panel on the right when you have configured both PROD and DEV endpoints on the Environments & API Keys page

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#255]
Currently the Help panel on the Environments & API Keys page is default open. Instead, conditionally close the panel if both PROD and DEV endpoints are configured. The `<Help/>` component on this page takes `defaultOpen` which you should use to add the conditional logic. 

![CleanShot 2023-08-03 at 16.45.04.png](https://uploads.linear.app/80a884b1-f84c-49d6-91db-07a391663d20/afdcb270-a2bd-4b59-a5a9-9f34ac51c322/ab335e1d-7168-4e4f-a358-8bf1d1840681?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYTg4NGIxLWY4NGMtNDlkNi05MWRiLTA3YTM5MTY2M2QyMC9hZmRjYjI3MC1hMmJkLTRiNTktYTVhOS05ZjM0YWM1MWMzMjIvYWIzMzVlMWQtNzE2OC00ZTRmLWEzNTgtOGJmMWQxODQwNjgxIiwiaWF0IjoxNjkxMDc4MDE2LCJleHAiOjE2OTExNjQ0MTZ9.sEz7C4RMqI7GZeA8BQI3R2hGLk-JRa2kizqYBjJVoFw)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-879](https://linear.app/triggerdotdev/issue/TRI-879/conditionally-hide-the-help-panel-on-the-right-when-you-have)</sub>

**Comment by MAYANK-TRIPATH** [comment]
@samejr Sorry By-mistake i deleted my attempt comment :(
