### ISSUE TITLE
[TRI-931] CLI create-integration should scaffold a job-catalog file

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#274]
When calling the `create-integration` CLI command from inside the monorepo, it should add a job-catalog file. Instead of the NextJS examples stuff it does currently.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-931](https://linear.app/triggerdotdev/issue/TRI-931/cli-create-integration-should-scaffold-a-job-catalog-file)</sub>

**Comment by Chigala** [comment]
I'm taking this up
