### ISSUE TITLE
[TRI-951] Remove resend dependency from the webapp and replace with nodemailer and smtp

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#282]
Now that Resend.com [supports sending email via SMTP](https://resend.com/blog/why-smtp-still-matters-today), we should convert the webapp to use a native SMTP mailer instead of the Resend SDK. We will need to replace the RESEND_API_KEY with SMTP_* environment variables (which should still be optional). When SMTP_* env vars are missing, we should continue to print the Magic Link login emails to the console how we are currently doing.

This will allow self-hosters to send email* without having to sign up to Resend.com and possibly use an existing email provider.

* Currently only used for Magic Link login

<sub>[TRI-951](https://linear.app/triggerdotdev/issue/TRI-951/remove-resend-dependency-from-the-webapp-and-replace-with-nodemailer)</sub>

**Comment by Chigala** [comment]
I'm taking this up

**Comment by Flowko** [comment]
any news on this ?
