### ISSUE TITLE
[TRI-999] Surface job queues in the dashboard

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#301]
Currently job queues are not displayed anywhere in the dashboard. We should display a list of job queues and show how many concurrent jobs are running for each queue. There should be a queue list and a queue detail page. 

<sub>[TRI-999](https://linear.app/triggerdotdev/issue/TRI-999/surface-job-queues-in-the-dashboard)</sub>

**Comment by evonloch** [comment]
Hey! I want to do this.

**Comment by ericallam** [comment]
Hey @evonloch, thanks for the enthusiasm but actually I'm going to close this because we've moved away from the existing queue stuff for now and will resurface it later with better support. It was a bit confusing and didn't really work that well so we removed it.
