### ISSUE TITLE
A new Express vanilla example?

### ISSUE THREAD

**Issue by lirantal** [triggerdotdev/trigger.dev#302]
## Description

Would you folks be keen on me adding an Express example app?

## Proposed changes

Looks like this `examples/` directory would be a good contribution to land an example application:

<img width="392" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/316371/134a0b01-ec93-4d0a-ba07-d2a1f31da0e2">

## Deliverables

Here's what I've had on my mind:

- [x] Minimal Express application
- [x] /api/trigger endpoint with `@trigger.dev/sdk` logic to handle trigger and jobs
- [x] A couple of endpoints: one to trigger an event from code, another to poll for data readiness
- [x] Example use-case builds on the OpenAI native Trigger.dev integration to keep it interesting
- [x] Frontend is kept to minimal and uses vanilla JavaScript to avoid complexity and frameworks fatigue

**Comment by ericallam** [comment]
This would be great! A couple of notes:

Using the `@trigger.dev/express` adapter means you don't need to setup the `/api/trigger` endpoint, just need to setup the middleware:

```ts
import express from "express";
import { TriggerClient } from "@trigger.dev/sdk";
import { createMiddleware } from "@trigger.dev/express";

const client = new TriggerClient({
 id: "my-client",
 apiKey: process.env["TRIGGER_API_KEY"]!,
});

const app = express();

const middleware = createMiddleware(client);

app.use(middleware);

app.listen(8080, () => {
 console.log("Listening on port 8080");
});
```

Also, the example should live in our dedicated examples repo: https://github.com/triggerdotdev/examples

The `examples` dir in the monorepo will probably be going away or renamed, as it's more of a testing ground for us and not true examples.

**Comment by lirantal** [comment]
> Using the @trigger.dev/express adapter means you don't need to setup the /api/trigger endpoint, just need to setup the middleware:

I know and I've planned to provide 2 example projects:
1. One which uses the official Express integration from Trigger.dev
2. One which builds on the SDK package and implements the /api/trigger logic on its own

Specifically I think (2) is important because it would empower developers to understand the abstraction and then easily port the implementation to other web servers: NestJS, Koa, etc.

--

I'll copy the issue + shoot out the PR to the examples repo as you noted. Thanks for clarifying!

**Comment by lirantal** [comment]
Addressed in https://github.com/triggerdotdev/examples/pull/3 so closing this one.
