### ISSUE TITLE
Removing the fetch fork from the Express package

### ISSUE THREAD

**Issue by lirantal** [triggerdotdev/trigger.dev#303]
## Expected results

The Express package at `@trigger.dev/express` uses the remix fork of a fetch implementation which IMHO adds an unnecessary dependency that is yet one more thing to maintain and worry about, and unnecessarily adds more code handling and import that don't help with readability.

Is there a specific reason to rely on `@remix-run/web-fetch` ? Node.js natively supports fetch.

## Actual results

I'm in favor of keeping things simple and straight-forward and would want to propose a code update that refactors the dependency out and implements the headers copy for the trigger.dev handshake via vanilla Node.js / JS code.

**Comment by ericallam** [comment]
Yea I'm totally with you on that one, I added that `@remix-run/web-fetch` dependency because we currently are targeting Node `>= 16.8.0`. So there are two options:

- Be convinced to support Node.js 18+ which has native fetch support
- Figure out another way to support Node.js 16.8+ without adding an extra dependency.

**Comment by lirantal** [comment]
Yep, I saw the engines support on the package.json file and figured that this will need to be an agreed-upon change :-)

Reasons to drop v16 support:
- v16 is on maintenance mode and will go end-of-life in 30 days (2023-09-11) so anyway no official support
- v18 is current and recommended LTS
- Trigger.dev is new and likely new projects adopting it will be using up-to-date Node.js runtime versions

Other ideas:
1. Delay this change to next month when v16 is officially announced end-of-life
2. Move the request conversion logic to the @trigger.dev/sdk to hide implementation details  rather than expose it on the integration

**Comment by ericallam** [comment]
Thanks for this, I'm leaning towards just ripping off the bandaid and going for v18 support sooner rather than later, but going to chat with the team and see what people think.
