### ISSUE TITLE
[TRI-1006] New `@trigger.dev/cli` whoami command. 

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#305]
Run it in a configured project and it will print out information about who you currently are. It will use the env vars (similar to how the dev command does) and the `trigger.dev` config data in package.json to print out useful information about the current setup. Some prior art:

https://devcenter.heroku.com/articles/heroku-cli-commands#heroku-auth-whoami
https://vercel.com/docs/cli/whoami

<sub>[TRI-1006](https://linear.app/triggerdotdev/issue/TRI-1006/new-triggerdevcli-whoami-command)</sub>

**Comment by neo773** [comment]
@ericallam can we close this?
