### ISSUE TITLE
Native node support

### ISSUE THREAD

**Issue by maximilian-schwarz** [triggerdotdev/trigger.dev#321]
Any plans for native node support?

**Comment by ericallam** [comment]
Do you mean support for working with a node server that uses the `http/s` module? We definitely could support that soon but we do currently only work with serverless deployments. Can you tell me a bit more about the use-case?

**Comment by maximilian-schwarz** [comment]
I often work with frameworks like NuxtJs. It would be greate to use trigger.dev with:

- VueJs
- NuxtJs (Maybe as VueJS Plugin)

**Comment by matt-aitken** [comment]
@maximilian-schwarz we have an open issue with PR for Nuxt support:
- Issue: #460 
- PR: #447 

I'm going to close this.=
