### ISSUE TITLE
[TRI-1079] Upgrade openai package to newest openai SDK release

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#344]
https://x.com/officiallogank/status/1691875240647758123?s=46&t=1ddbpEADp3fME9hP7W6tsg

<sub>[TRI-1079](https://linear.app/triggerdotdev/issue/TRI-1079/upgrade-openai-package-to-newest-openai-sdk-release)</sub>

**Comment by lazyfuhrer** [comment]
Hey I'd like to work on this. Can you tell me more about this ? @ericallam

**Comment by ericallam** [comment]
@lazyfuhrer yea that'd be great! Basically it is what it sounds like, we currently use `3.3.0` in our `@trigger.dev/openai` integration and we'd like to upgrade that to use the new `4.0` release

**Comment by lazyfuhrer** [comment]
Great! I'd like to go ahead. Assign me @ericallam

**Comment by lazyfuhrer** [comment]
![pnpm](https://github.com/triggerdotdev/trigger.dev/assets/64888892/16ea8502-6fae-4373-8af1-c90515809c13)
I'm trying to update the openai package but getting this. Any guess how to fix it ? I'm new to pnpm @ericallam

**Comment by ericallam** [comment]
@lazyfuhrer I went ahead and started the migration here: https://github.com/triggerdotdev/trigger.dev/pull/383

**Comment by nicktrn** [comment]
Completed in #383
