### ISSUE TITLE
[TRI-1124] Bug: `@trigger.dev/cli init` incorrectly misses detection of app dir usage in some cases

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#373]
See this tweet: https://twitter.com/arthurliebhardt/status/1693585989892026517

It seems in some cases the app dir isn't correctly being detected, and the pages dir is being incorrectly assumed.

<sub>[TRI-1124](https://linear.app/triggerdotdev/issue/TRI-1124/bug-triggerdevcli-init-incorrectly-misses-detection-of-app-dir-usage)</sub>

**Comment by arthurliebhardt** [comment]
Hello,
I'm using app dir without src directory and jsx files.

**Comment by ericallam** [comment]
Yup it looks like the issue is the one @Chigala mentioned above, will get it fixed up and released ASAP. Thanks for confirming @arthurliebhardt!

**Comment by Chigala** [comment]
@arthurliebhardt does it detect pages directory for you? I just tested it on my machine and can confirm .jsx extensions in app directory breaks the code.
