### ISSUE TITLE
[TRI-1125] `@trigger.dev/cli init` reports the wrong file name for app dir and javascript projects

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#376]
I just ran `@trigger.dev/cli init` against a Next.js project using the App Dir and JavaScript and it output the following message:

```
✅ Created app route at src/app/api/trigger.ts
```

Even though the file was actually created at `src/app/api/trigger/route.js`

We should make sure that this output is correctly specified for different setups:

- [ ] App Dir w/ JS
- [ ] App Dir w/ TS
- [ ] Pages Dir w/ JS
- [ ] Pages Dir w/ TS

<sub>[TRI-1125](https://linear.app/triggerdotdev/issue/TRI-1125/triggerdevcli-init-reports-the-wrong-file-name-for-app-dir-and)</sub>

**Comment by Chigala** [comment]
I'll look into this
