### ISSUE TITLE
How to increase the queue limit 

### ISSUE THREAD

**Issue by S0c5** [triggerdotdev/trigger.dev#386]
Today we face an issue where many of our task jobs are queued, how can increase the number of task jobs alive?

<img width="1608" alt="Screen Shot 2023-08-23 at 3 09 28 PM" src="https://github.com/triggerdotdev/trigger.dev/assets/5241972/95fce766-8581-49ef-948d-8951d63b6428">

**Comment by ericallam** [comment]
@S0c5 where were you running this? Using the Trigger.dev cloud or self-hosting?

**Comment by S0c5** [comment]
Using self-hosting.

**Comment by ericallam** [comment]
We actually recently released a fix for this and it's available at v2.0.0-beta.28:

https://github.com/triggerdotdev/trigger.dev/pkgs/container/trigger.dev/120477246?tag=v2.0.0-beta.28

Details about the changes can be found here:

https://github.com/triggerdotdev/trigger.dev/pull/360

**Comment by S0c5** [comment]
Hey @ericallam after the update the tasks still in queued status, there is a way to increase the limit or run those task manually?

**Comment by ericallam** [comment]
You should be able to Cancel them and then Retry

![CleanShot 2023-08-23 at 21 34 44@2x](https://github.com/triggerdotdev/trigger.dev/assets/534/5edc7738-d2e2-46c8-8e52-346954a8fb6e)

**Comment by S0c5** [comment]
@ericallam thanks very much for your quick reply, is there a programmatic way to do it? we have like 200 jobs 😢

**Comment by ericallam** [comment]
@S0c5 I wish I had a better answer for you there but unfortunately I do not. Will be creating an issue for this now

**Comment by ericallam** [comment]
https://github.com/triggerdotdev/trigger.dev/issues/388
