### ISSUE TITLE
[TRI-1135] Add job management API endpoints

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#388]
We need to flesh out our API to allow you to manage jobs and runs:

- Get a list of runs for a specific job (with filtering for status, environment, etc.)
- Get task data for a specific run
- Cancel a run
- Retry a run
- Resume a run
- Test a job

These would ideally all be exposed via the `TriggerClient` class and would require the Server API Key to access.

<sub>[TRI-1135](https://linear.app/triggerdotdev/issue/TRI-1135/add-job-management-api-endpoints)</sub>

**Comment by matt-aitken** [comment]
@ericallam you can already get runs for a job, and get info about a run using the SDK

**Comment by ericallam** [comment]
@matt-aitken private data or just public?

**Comment by ericallam** [comment]
BTW the reason I created this issue is because of this scenario:

https://github.com/triggerdotdev/trigger.dev/issues/386#issuecomment-1690604407

**Comment by ericallam** [comment]
Hold off on working on this for now, I think there's a discussion that needs to be had first about if it makes sense to use the Project API Key's for these management API endpoints or if we should have another type of API key that works across projects & environments. A sort of "Personal Access Token" type API Key, similar to the Supabase Management API works

**Comment by matt-aitken** [comment]
@Chigala @fvckDesa don't work on this. We need to think more about how this works.

**Comment by ericallam** [comment]
Yea this feature will require a new type of API Key called a Personal Access Token:

![CleanShot 2023-08-24 at 10 15 57](https://github.com/triggerdotdev/trigger.dev/assets/534/60c24e8d-23b0-4eec-a5c5-f5eb05cc3c76)

These API Keys have authorization the "Management APIs", some of which are mentioned above. The endpoints should be different from our current API endpoints (maybe something like `/manage/api/v1/...`

You should be able to create multiple personal access tokens, and we don't create one for you by default. The PAT should look like `tr_pat_XXXXXXXXXXXXXX`.

**Comment by Chigala** [comment]
@ericallam  using personal access tokens for the management APIs makes more sense. This is  how the PAT table would be modelled right? 
```
model PersonalAccessToken {
  id                String      @id @default(cuid())
  token             String    @unique
  revoked           Boolean   @default(false)
  revokedAt         DateTime?
  lastAccessedAt    DateTime
  userId            String    
  user              User      @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
}
```
When a PAT is revoked, should we just take this my approach of a soft delete or remove the token from the DB?

**Comment by ericallam** [comment]
Yea I think you don't need the `revoked` column, you can just use `revokedAt`. Also `lastAccessedAt` should be optional. everything else looks good

**Comment by Chigala** [comment]
Ohk, Thanks. Are there any more changes on your end about this? If no, that means I can start working on it right?

**Comment by ericallam** [comment]
@Chigala I would let @neo773 take this one for now, as he started on it last night

**Comment by Chigala** [comment]
That's ohk

**Comment by dennismzia** [comment]
this seems easy why and august in the tech world is ages ago so how comes no one has finished it. or claimed the reward
anyways is this still open ?

**Comment by neo773** [comment]
@dennismzia I had a PR for this but the trigger management have put it on hold for now.

**Comment by andrewlu0** [comment]
I would really benefit from this functionality as right now our end users have no way of retrying a job run if it fails. Either a management API or even returning the run's payload info in getRun() or useEventRunDetails(), would enable users to retry failed runs. Is there any update on this?

**Comment by ericallam** [comment]
@andrewlu0 we've recently released a new API for exposing run data to the public called Run Statuses:

https://trigger.dev/docs/documentation/guides/react-hooks-statuses

Would that help in your case?

**Comment by VirtualDharm** [comment]
/attempt https://github.com/triggerdotdev/trigger.dev/issues/388

Options
[Cancel my attempt](https://console.algora.io/api/bounties/cllo7nk1r0002l60fcxgjv4i4/cancel-attempt)

**Comment by rishi-raj-jain** [comment]
@ericallam Can I work on this?

**Comment by neo773** [comment]
@rishi-raj-jain 
They put it on hold since they needed a few prerequisite changes prior to merging my PR.
Not sure what the status is now.
 You could use my closed PR as base if you'd wish https://github.com/triggerdotdev/trigger.dev/pull/406

**Comment by Bhavyajain21** [comment]
Can I be assigned? @matt-aitken

**Comment by Sanskar711** [comment]
@ericallam is this issue still open can i work on it??

**Comment by 0xa48rx394r83e9** [comment]
This looks like an intriguing feature to build, and I'm eager to work on it, but I'd like to just clarify that the bounty is still open and that the scope/parameters of the bounty haven't changed (since it's been nine months).

**Comment by techsouvik** [comment]
Can I be assigned? @matt-aitken @ericallam

**Comment by FayadIdriss** [comment]
Je peux travailler sur ce ticket, je peux être assigné ?

**Comment by FayadIdriss** [comment]
Je peux travailler sur ce ticket, je peux être assigné ? @ericallam @matt-aitken

**Comment by KyleChen26** [comment]
Hi! I'd like to work on this bounty.

**Approach:**
1. Add `TriggerClient` methods for job/run management:
   - `getRuns(jobId, filters)` - list runs with status/env filtering
   - `getRunTaskData(runId)` - get task data for a run
   - `cancelRun(runId)` - cancel running job
   - `retryRun(runId)` - retry failed job
   - `resumeRun(runId)` - resume paused job
   - `testJob(jobId, payload)` - trigger test run

2. Add corresponding Server API endpoints that require API key
3. Include TypeScript types and error handling
4. Add tests for new endpoints

**Deliverables:**
- Extended TriggerClient class with new methods
- Server API route handlers
- Type definitions
- Unit tests

**ETA:** 3-5 days

Can I take this?
