### ISSUE TITLE
[TRI-1163] CLI dev command tunnel doesn't work if you're already running ngrok

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#403]
It just hangs on this, without providing an error message:

![CleanShot 2023-08-26 at 12.22.37.png](https://uploads.linear.app/80a884b1-f84c-49d6-91db-07a391663d20/6057e96f-27e0-420a-8399-d57eaf0ef68b/00d85346-bdc1-42e8-a387-3e42404f00f2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYTg4NGIxLWY4NGMtNDlkNi05MWRiLTA3YTM5MTY2M2QyMC82MDU3ZTk2Zi0yN2UwLTQyMGEtODM5OS1kNTdlYWYwZWY2OGIvMDBkODUzNDYtYmRjMS00MmU4LWEzODctM2U0MjQwNGYwMGYyIiwiaWF0IjoxNjkzMDQ5NTMyLCJleHAiOjE2OTMxMzU5MzJ9.DkB-daC3xX89yS1VWa6RlQ3dqMxKCYxgoHKJqwSrL30)

Is it possible to create a tunnel when there is already one running? Perhaps by using the options when creating it?

If not we should display a message to tell the user it won't work when they're already running ngrok.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1163](https://linear.app/triggerdotdev/issue/TRI-1163/cli-dev-command-tunnel-doesnt-work-if-youre-already-running-ngrok)</sub>

**Comment by Chigala** [comment]
I just looked into this, with the command line you can only serve one port with a free account, although if you use a configuration file serve up to two with one command. [Setting up multiple ports with ngrok](https://dev.to/ethand91/using-ngrok-to-set-up-multiple-ports-2911). 

I don't think we can use the options for this, although I might be wrong, the best we could do would be maybe display a message like you said.
