### ISSUE TITLE
Extend Stripe Triggers Support for Payment Intents, Payouts, and Account Links

### ISSUE THREAD

**Issue by gjohnsx** [triggerdotdev/trigger.dev#413]
## Feature Request: Extend Stripe Triggers Support for Payment Intents, Payouts, and Account Links

I'd like to request Trigger.dev to extend Stripe trigger support for additional functionalities:

### [Payment Intents](https://stripe.com/docs/api/payment_intents)
- `onPaymentIntentCreated` (`stripe.paymentIntents.create`)
- `onPaymentIntentUpdated` (`stripe.paymentIntents.update`)
- `onPaymentIntentConfirmed` (`stripe.paymentIntents.confirm`)
- `onPaymentIntentCaptured` (`stripe.paymentIntents.capture`)
- `onPaymentIntentCanceled` (`stripe.paymentIntents.cancel`)

### [Payouts](https://stripe.com/docs/api/payouts)
- `onPayoutCreated` (`stripe.payouts.create`)
- `onPayoutUpdated` (`stripe.payouts.update`)
- `onPayoutCanceled` (`stripe.payouts.cancel`)
- `onPayoutReversed` (`stripe.payouts.reverse`)

### [Account Links](https://stripe.com/docs/api/account_links)
- `onAccountLinkCreated` (`stripe.accountLinks.create`)

These triggers are essential for building a comprehensive platform with Stripe Connect.

Thank you for considering this request.

**Comment by ericallam** [comment]
I've added triggers for PaymentIntents and Payouts here: 

https://github.com/triggerdotdev/trigger.dev/commit/a10782490fd2764fde40beff4331da89a57e1f16

Unfortunately Stripe do not expose webhook events for Account Links at the moment.

**Comment by gjohnsx** [comment]
Great, thank you very much!
