### ISSUE TITLE
Shopify New Order Webhook

### ISSUE THREAD

**Issue by mehmetuken** [triggerdotdev/trigger.dev#42]
Document: https://shopify.dev/api/admin-rest/2022-04/resources/webhook

**Comment by ericallam** [comment]
Are there specific webhook events from Shopify that you particular want to use?

**Comment by guido4000** [comment]
I suppose he meant the following event:

https://shopify.dev/api/admin-rest/2022-04/resources/webhook#event-topics-orders-create
