### ISSUE TITLE
[TRI-1171] Add to docs: note about https://github.com/nextauthjs/next-auth/issues/7660

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#423]
Users on Next.js 13.4.4 will run into the error linked in the title, we should add this to the docs in the Next.js platform guide

<sub>[TRI-1171](https://linear.app/triggerdotdev/issue/TRI-1171/add-to-docs-note-about-httpsgithubcomnextauthjsnext-authissues7660)</sub>

**Comment by hrutik7** [comment]
hey @ericallam is this looks good to you ?
![image](https://github.com/triggerdotdev/trigger.dev/assets/62372737/94d60f81-2fc3-49a9-95ed-93ec61685c63)
Or I need to change a bit ?
