### ISSUE TITLE
[TRI-1200] `@trigger.dev/stripe` triggers should not allow invalid events

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#426]
Currently we don't do any client-side filtering of events passed to triggers:

```
stripe.onPrice({ events: ["price.created", "this.is.invalid"] })
```

Other than TypeScript errors, nothing will stop the above trigger to attempt to register the `this.is.invalid` event, which will result in an error response from the Stripe API. We should filter these out (and print a warning) to prevent this issue.

<sub>[TRI-1200](https://linear.app/triggerdotdev/issue/TRI-1200/triggerdevstripe-triggers-should-not-allow-invalid-events)</sub>

**Comment by duckling69** [comment]
Hey @ericallam I'd like to work on this issue
