### ISSUE TITLE
[TRI-1226] Allow seeing teammates' dev runs

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#435]
When on the runs page for a job you currently only see runs associated with your personal Dev environment – you DO NOT see runs from your teammates Dev environment.

## Options

1. Keep it as-is, but add a filter dropdown where you can select environments. Teammate Dev environments would be unchecked by default when you load the page.
2. Show all Dev environments by default. Filters can be added later.

I think option 2 is the correct choice.

## Display style

Your own Dev environment would remain as-is: `[DEV]`.
Teammate's would appear like this: `[DEV: Amy]`.

## Changes required

* Add an optional name param on the `EnvironmentLabel`.
* Change the `RunListPresenter` so it doesn't filter the environments in the where clause. Get the name of the user for the environment.
* The RunTable would need to be adapted to pass in the name (note this only applies to DEV environments).
* On the Run page, update the environment badge

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1226](https://linear.app/triggerdotdev/issue/TRI-1226/allow-seeing-teammates-dev-runs)</sub>

**Comment by banderson12** [comment]
This would be very helpful.

**Comment by RamK777-stack** [comment]
Would like to work on this !!

**Comment by Slyracoon23** [comment]
Is there any progress on this?
