### ISSUE TITLE
[TRI-1230] TypeScript "Type instantiation is excessively deep and possibly infinite.ts(2589)" error when using eventTrigger w/zod schema (different Zod versions)

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#436]
When using the `eventTrigger` with zod to define the event schema TypeScript gives this error:

![](https://uploads.linear.app/80a884b1-f84c-49d6-91db-07a391663d20/4bca3b0b-e32b-420d-8198-f5f3e52d8733/66f377c7-1a97-42ec-b5ad-8b4c4974672c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYTg4NGIxLWY4NGMtNDlkNi05MWRiLTA3YTM5MTY2M2QyMC80YmNhM2IwYi1lMzJiLTQyMGQtODE5OC1mNWYzZTUyZDg3MzMvNjZmMzc3YzctMWE5Ny00MmVjLWI1YWQtOGI0YzQ5NzQ2NzJjIiwiaWF0IjoxNjkzOTMzMjU5LCJleHAiOjE2OTQwMTk2NTl9.f8-Cl_2WEvsRxv1wuGksLGbbDnPNRK2uvoC2R60AYSE)

This only seems to be happening in Next.js projects created with `create-t3-app`. I've reproduced it here:

[https://github.com/ericallam/t3-trigger-app/blob/bbade197052ae5d790c7b46509628a5c8d57ba94/src/jobs/examples.ts#L19](https://github.com/ericallam/t3-trigger-app/blob/bbade197052ae5d790c7b46509628a5c8d57ba94/src/jobs/examples.ts#L19)

We need to track down the issue and figure out how to fix it (or provide a workaround for t3-app)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1230](https://linear.app/triggerdotdev/issue/TRI-1230/typescript-possibly-infinite-error-when-using-eventtrigger-wzod-schema)</sub>

**Comment by ericallam** [comment]
It would be great to track down exactly what the issue is and:

1. Document the issue
2. Open an issue on Zod repo with with a reproduction repo
3. If there is a way for us to fix the issue, do that as well

**Comment by nicktrn** [comment]
Fixed by #500
