### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [triggerdotdev/trigger.dev#443]
### Bug Description
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### ScreenShot
<img width="960" alt="Screenshot 2023-09-07 163228" src="https://github.com/triggerdotdev/trigger.dev/assets/91591901/4c444d0d-f102-486b-955f-226b110673ce">

### Expected Behavior
Change the old logo with the new one.

### Request
@ericallam 
I want to work on this issue please assign this to me.

**Comment by samejr** [comment]
Hi @lalitkumawat1m unfortunately, our marketing site isn't open sourced so we'll have to update this internally. 

Thanks for your suggestion though. Feel free to check out some of the [other issues](https://github.com/triggerdotdev/trigger.dev/issues) if you want to contribute – or open another issue you want to work on.
