### ISSUE TITLE
[TRI-1296] feat: CLI dev should work with injected environment variables

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#509]
### Is your feature request related to a problem? Please describe.

The CLI dev command fails if you don't use .env files – instead using something like 1Password to inject the values.

### Describe the solution you'd like to see

Make the @trigger.dev/cli first check if the TRIGGER_API_KEY is defined in the current process.

### Additional information

This is the relevant code: [https://github.com/triggerdotdev/trigger.dev/blob/main/packages/cli/src/utils/getTriggerApiDetails.ts#L36](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/cli/src/utils/getTriggerApiDetails.ts#L36)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1296](https://linear.app/triggerdotdev/issue/TRI-1296/feat-cli-dev-should-work-with-injected-environment-variables)</sub>

**Comment by matt-aitken** [comment]
Thank's for opening this issue!

**Comment by Chigala** [comment]
Hey @matt-aitken please assign this to me

**Comment by matt-aitken** [comment]
@Chigala thanks! We're announcing our Hacktoberfest competition in a couple of days. This issue is now tagged with it
