### ISSUE TITLE
[TRI-1301] Add support for Deno

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#510]
This would require adding an adaptor, docs and CLI support.

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1301](https://linear.app/triggerdotdev/issue/TRI-1301/add-support-for-deno)</sub>

**Comment by guy-borderless** [comment]
replied in #515

**Comment by matt-aitken** [comment]
This is duplicated by #515
