### ISSUE TITLE
[TRI-1309] Trigger registration errors don't get displayed to the user

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#514]
### To reproduce

Add a job with an `intervalTrigger` with a very large value for the seconds (greater than `2_592_000`). The Job will silently fail to appear in the dashboard.

### Expected result

The error should get returned from the registration endpoint so it's shown in the user's local development console (where they run `npx @trigger.dev/cli@latest dev`). 

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1309](https://linear.app/triggerdotdev/issue/TRI-1309/trigger-registration-errors-dont-get-displayed-to-the-user)</sub>

**Comment by arpittiwari24** [comment]
Hey @matt-aitken  
Can I go ahead with solving this issue ?

**Comment by matt-aitken** [comment]
@arpittiwari24 yep that sounds great! I'll also add it to our Hacktoberfest, which will start in a couple of days and means you can get some swag if we merge it.

**Comment by Kritika30032002** [comment]
Assign me this

**Comment by arpittiwari24** [comment]
Hey @Kritika30032002  I am still working on this issue.

**Comment by matt-aitken** [comment]
@Kritika30032002 @arpittiwari24 sorry we've removed this from Hacktoberfest. It's a complicated issue that is going to require some complex platform changes that require a lot of internal knowledge to solve in a way that makes sense.
