### ISSUE TITLE
[TRI-1310] Add a Deno adaptor

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#515]
This have a pre-requisite before it's possible:

\#252

### What needs to be done?

After the above issue is completed, the adaptor should be straight forward.

A new adaptor in `packages/deno` needs to be created. There are several to look at as inspiration, the simplest being Remix: [https://github.com/triggerdotdev/trigger.dev/blob/main/packages/remix/src/index.ts](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/remix/src/index.ts)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1310](https://linear.app/triggerdotdev/issue/TRI-1310/add-a-deno-adaptor)</sub>

**Comment by guy-borderless** [comment]
As far as my tests show #252 doesn't seem to be a blocker for deno, deno imports trigger.dev libraries with the `npm:` specifier correctly.  e.g.
`import { eventTrigger, TriggerClient } from "npm:@trigger.dev/sdk"
import { z } from "npm:zod"

export const client = new TriggerClient({
  id: "job-catalog",
  apiKey: "...",
  verbose: false,
  ioLogLocalEnabled: true,
})
`

Seems problems only arise where the existence of package.json is assumed, like in the [cli here](https://github.com/triggerdotdev/trigger.dev/blob/f888a49555542b80968bf26b80cb4ee8a1151fd2/packages/cli/src/commands/dev.ts#L61)
We can just look for package.json or deno.json, also we can first check for the endpointId in the environment variable.

**Comment by matt-aitken** [comment]
@guy-borderless that's great that it's possible by using the npm prefix on imports.

Looking in an environment variables first for the endpointId is a really good idea 👍 

I was hoping we could add automatic setup for Deno to our CLI in the init command. But it's bit complicated because Deno is a runtime not a framework. It wouldn't really make sense for us to add a new Deno framework to this list I don't think: https://github.com/triggerdotdev/trigger.dev/blob/e350659e244e6976747f726984c83a780ba94882/packages/cli/src/frameworks/index.ts#L56.

We could add a very simple Deno "framework" which is similar to the Express one. It sets up what it can and prints out further instructions which would point you at the docs? @guy-borderless what do you think?

**Comment by guy-borderless** [comment]
Yeah, it's a runtime and runs express, astro ext.  It also has a built in http server, so an example for usage could be:
`import { TriggerClient } from "npm:@trigger.dev/sdk";
import { eventTrigger } from "npm:@trigger.dev/sdk";

export const triggerClient = new TriggerClient({
    id: "borderless",
    apiKey: "...",
});


// your first job
triggerClient.defineJob({
    id: "example-job",
    name: "Example Job",
    version: "0.0.1",
    trigger: eventTrigger({
        name: "example.event",
    }),
    run: async (payload, io, ctx) => {
        await io.logger.info("Hello world!", { payload });

        return {
            message: "Hello world!",
        };
    },
});


Deno.serve(async (req) => {
    const response = await triggerClient.handleRequest(req);
    if (!response) {
        return Response.json({ error: "Not found" }, {
            status: 404,
        })
    }

    return Response.json(response.body, {
        status: response.status,
        headers: new Headers(response.headers)
    });
});` 

just recently I started working on the dev command, it shouldn't be too difficult to separate the runtime away. I'm doing some refactoring to centralize the runtime specific references, which will also be helpful for cloudflare workers later on. Also the tidy up the code. The built in HTTP server doesn't have a middleware concept and the trigger express middleware (and probably the Astro too) seem to work as is on deno. 
 What I think would be nice for web API runtimes like deno and CF workers is to have `triggerClient.handleRequest` return a proper `Response()` or maybe have a `toWebResponse()` method on the returned (`NormalizedResponse`) object. Should I add that?

**Comment by matt-aitken** [comment]
I like the idea of adding a `toWebResponse()` function on NormalizedResponse. @ericallam this one is your domain, what do you think?

**Comment by guy-borderless** [comment]
> I like the idea of adding a `toWebResponse()` function on NormalizedResponse. @ericallam this one is your domain, what do you think?

triggerClient.handleWebRequest
also an option
