### ISSUE TITLE
[TRI-1333] [TRI-1332] Upgrade all packages/* and use fetch instead of node-fetch

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#525]
## Problem

Our packages currently support Node 16–17. This means we can't use `fetch` and we can't support some modern deployment platforms like Cloudflare/Vercel edge functions.

Node v18 is now LTS and v16 has entered "end-of-life" with no official support.

## Solution

* Set the engines.node property in all of the packages/\*/package.json files.
* Upgrade all packages/\* to support Node v18. 
* Change fetch to node-fetch
* Fix any other issues
* Ensure that typechecking has no errors: `pnpm run --filter "./packages/**" typecheck`

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1332](https://linear.app/triggerdotdev/issue/TRI-1332/upgrade-all-packages-and-use-fetch-instead-of-node-fetch)</sub>

<sub>[TRI-1333](https://linear.app/triggerdotdev/issue/TRI-1333/[tri-1332]-upgrade-all-packages-and-use-fetch-instead-of-node-fetch)</sub>

**Comment by priyankarpal** [comment]
I would like to work on this issue. please assign to me @matt-aitken

**Comment by Rutam21** [comment]
@matt-aitken I would like to work on this. Please assign this to me. Thanks.

**Comment by ruhankhandakar** [comment]
Hi @matt-aitken I would like to upgrade all packages. Please assign it to me.

**Comment by ericallam** [comment]
Something to be aware of

https://github.com/nodejs/undici
