### ISSUE TITLE
bug: useEventDetails Hook Returns 'Data is Undefined' Error for Valid Event ID

### ISSUE THREAD

**Issue by Slyracoon23** [triggerdotdev/trigger.dev#547]
### Provide environment information

  System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 17.27 GB / 31.13 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm

### Describe the bug

When using the useEventDetails hook that takes an event_id, I'm encountering an error message: `Error: ["triggerdotdev-event-01HBWY7FZB9S11VF2R87FCY623"] data is undefined.`

## Expected behavior:
The hook should return the details associated with the provided event_id without any errors.

### Reproduction repo

https://gist.github.com/Slyracoon23/7cbce69741cea76f3a6fe71ffda52ba3

### To reproduce

1. Use the useEventDetails hook from @trigger.dev/react.
2. Pass a valid event_id to the hook.
3. Observe the error message: `Error: ["triggerdotdev-event-01HBWY7FZB9S11VF2R87FCY623"] data is undefined.`

I know that EventID is valid because EventId using `await client.getEvent("01HBWY7FZB9S11VF2R87FCY623");`  returns

```
Event: {
  id: '01HBWY7FZB9S11VF2R87FCY623',
  name: 'discord.fetch.all.messages',
  createdAt: 2023-10-04T08:52:47.212Z,
  updatedAt: 2023-10-04T08:52:47.223Z,
  runs: [
    {
      id: 'clnbigffac9bnlv3n7mqgrs8a',
      status: 'CANCELED',
      startedAt: 2023-10-04T08:52:47.289Z,
      completedAt: 2023-10-04T09:19:42.719Z
    }
  ]
}
```

### Additional information

const { isLoading, isError, data, error } = eventId ? useEventDetails(eventId) : { isLoading: false, isError: false, data: null, error: null };

https://www.loom.com/share/ab1df1d29c724bc795ed0fe65d3867f3?sid=93273700-5f6b-4194-aa49-cb7bbfaa2497

**Comment by Slyracoon23** [comment]
I also tried this with `useEventRunDetails` and don't get any returned job

**Comment by hmacr** [comment]
@Slyracoon23 @ericallam  I'm able to reproduce this issue by using an incompatible public API key for the `useEventDetails` hook.

Could you check if the API key passed to the [TriggerProvider](https://trigger.dev/docs/sdk/react/triggerprovider) is for the environment where the event is created?

**Comment by Slyracoon23** [comment]
I think I solved the issue @hmacr. I didn't have a wrong key but I did have a url that may be wrong. 
I set `NEXT_PUBLIC_TRIGGER_API_URL=http://localhost:3000`


Old
```
  <TriggerProvider
              publicApiKey={
                process.env.NEXT_PUBLIC_CLIENT_TRIGGER_API_KEY ?? ""
              }
              apiUrl={process.env.NEXT_PUBLIC_TRIGGER_API_URL}
            >
              {children}
            </TriggerProvider>
  ```
  
  New
  
 ```
   <TriggerProvider
              publicApiKey={
                process.env.NEXT_PUBLIC_CLIENT_TRIGGER_API_KEY!}
              // apiUrl={process.env.NEXT_PUBLIC_TRIGGER_API_URL!}
            >
              {children}
            </TriggerProvider>
 ```
            
I removed it entirely and it has fixed the issue
