### ISSUE TITLE
[TRI-1361] [TRI-1360] Allow deleting Endpoints in the UI

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#551]
## Problem

You can easily create a new endpoint by changing the id in the TriggerClient constructor. But there's currently no way to get rid of them.

## Solution

Add the ability to delete them in the UI. We need to warn users with information about the impact of their change before doing the delete. 

I imagine a panel a bit like the delete job panel but it would have a list of the Jobs that are associated with the endpoint. We could allow users to delete it if they type the name of the endpoint id into an input field, and then press the button.

<img width="589" alt="CleanShot 2023-10-04 at 14 52 21@2x" src="https://github.com/triggerdotdev/trigger.dev/assets/10635986/b119322d-b5f1-4ccb-90cc-6c0fb5755450">

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1360](https://linear.app/triggerdotdev/issue/TRI-1360/allow-deleting-endpoints-in-the-ui)</sub>

**Comment by ericallam** [comment]
The other option would be to get rid of endpoint slugs altogether and only allow a single endpoint per environment

**Comment by matt-aitken** [comment]
@ericallam I don't think we can do that because it would mean if you had two separate deployed services you couldn't have Jobs on both, and send events between them.

**Comment by danielHype** [comment]
What is the status here? Have the same issue.
