### ISSUE TITLE
[TRI-1363] feat: Allow cancelling job runs from the TriggerClient

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#554]
### Is your feature request related to a problem? Please describe.

There is currently no way to cancel a job run programmatically.

### Describe the solution you'd like to see

It would be great if there was an instance method exposed on `TriggerClient` that allowed cancelling a run:

```ts
await client.cancelRun(runId)
```

This will require a new endpoint `POST /api/v1/runs/$runId/cancel`.  It should use the `CancelRunService` which is used when cancelling a run from the dashboard. The response body should be the same response as the `GET /api/v1/runs/$runId` endpoint.

### Describe alternate solutions

N/A

<sub>[TRI-1363](https://linear.app/triggerdotdev/issue/TRI-1363/feat-allow-cancelling-job-runs-from-the-triggerclient)</sub>

**Comment by 0x0elliot** [comment]
hey, i would like to take up this issue :)

**Comment by 0x0elliot** [comment]
done!

**Comment by 0x0elliot** [comment]
a bit of management and head's up would be cool to not do the same issue someone else is doing! @ericallam

**Comment by 0x0elliot** [comment]
this makes me unsure if i want to do other issues that i think i can do right now because:

- i feel like me making a PR first does not matter anymore. 
- someone else would make a PR and you wouldn't work with mine, without much explanation behind your decision. 

what do you think?
