### ISSUE TITLE
[TRI-1364] feat: Switch to Sonner toasts

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#555]
We currently use toasts in our dashboard in a few places which are powered by "react-hot-toast". We should upgrade to Sonner toasts as they have some pretty cool features and look great:

https://github.com/emilkowalski/sonner

<sub>[TRI-1364](https://linear.app/triggerdotdev/issue/TRI-1364/feat-switch-to-sonner-toasts)</sub>

**Comment by gupta-piyush19** [comment]
Hi @ericallam! I'd like to work on this. Can you please assign this to me?

**Comment by Saurav-Pant** [comment]
I am interested in resolving this issue, please assign it to me @ericallam

**Comment by ericallam** [comment]
We're not assigning issues, we'll accept the best PR for an issue (not necessarily the first PR either). Triaging assignments during hacktoberfest doesn't scale.
