### ISSUE TITLE
[TRI-1366] fix: JobRun needs an internal boolean column, to reflect the value in Job

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#557]
We use internal jobs for things like webhook registration, and those jobs have `internal = true` set in the database. We also need to add an `internal` column to JobRun that is set to `true` when the job it's associated with is `internal = true`. This is just denormalization, so when we do usage queries (in the new usage page) we can easily eliminate internal runs from the usage. The migration for this should upgrade existing runs to the correct `internal` value.

<sub>[TRI-1366](https://linear.app/triggerdotdev/issue/TRI-1366/fix-jobrun-needs-an-internal-boolean-column-to-reflect-the-value-in)</sub>

**Comment by 0x0elliot** [comment]
interesting. so literally, just add in "internal" with the default value as "true" in the postgres ts migrations?

can you assign this issue to me please? :)

**Comment by 0x0elliot** [comment]
probably not this since it's already here 🤔 
<img width="916" alt="Screenshot 2023-10-05 at 7 41 23 AM" src="https://github.com/triggerdotdev/trigger.dev/assets/60684641/da4a0790-c734-4886-ae1a-3a28284c8ff0">

**Comment by karti16** [comment]
@0x0elliot the 'JobRun' table internal column should have value based on 'Job' table internal column. While creating new jobrun value can be set. But I can't come up how to set values for the existing jobrun rows in the table.

**Comment by karti16** [comment]
> probably not this since it's already here 🤔 
> <img width="916" alt="Screenshot 2023-10-05 at 7 41 23 AM" src="https://github.com/triggerdotdev/trigger.dev/assets/60684641/da4a0790-c734-4886-ae1a-3a28284c8ff0">
> 
> 

To be added in JobRun table

**Comment by 0x0elliot** [comment]
oh that makes sense. are you handling this then :)? 

> > probably not this since it's already here 🤔
> > <img alt="Screenshot 2023-10-05 at 7 41 23 AM" width="916" src="https://user-images.githubusercontent.com/60684641/272760874-da4a0790-c734-4886-ae1a-3a28284c8ff0.png">
> 
> To be added in JobRun table

**Comment by karti16** [comment]
> oh that makes sense. are you handling this then :)? 
> 
> > > probably not this since it's already here 🤔
> > > <img alt="Screenshot 2023-10-05 at 7 41 23 AM" width="916" src="https://user-images.githubusercontent.com/60684641/272760874-da4a0790-c734-4886-ae1a-3a28284c8ff0.png">
> > 
> > To be added in JobRun table
> 
> 

I may need some help. I didn't start working on this. If you can figure out. That's okay too.

**Comment by 0x0elliot** [comment]
i might be able to solve this quick. i haven't slept today however, so no promises :P 

i hope that's okay? @karti16

**Comment by 0x0elliot** [comment]
https://github.com/triggerdotdev/trigger.dev/pull/561

will do the testing in a bit. please wait for my thumbs up before merge :3

**Comment by karti16** [comment]
@0x0elliot working as expected ?

**Comment by hmacr** [comment]
@ericallam I've created two PRs (#563 and #564) for this change.

#563 - adds the new `internal` column and sets its value accordingly in the `createRun` API.
#564 - Backfill script for the new `internal` column.

#564 builds on top #563.
The intention is to separate the schema and API change from the backfill script. This way, the jobs & job runs that get created during the backfill execution can still have the correct internal flags set (the API takes care of it).

Hope this helps.
