### ISSUE TITLE
[TRI-1367] feat: Allow cancelling all job runs for a given event ID

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#565]
### Is your feature request related to a problem? Please describe.

After #554 is done, we also need to support cancelling runs that were triggered via a specific event ID

### Describe the solution you'd like to see

We should add an instance method to `TriggerClient` called `cancelRunsForEvent` that accepts a single parameter that is an `eventID`, which will hit a new API endpoint `/api/v1/events/$eventId/cancel-runs` that will query for all cancellable runs and then call the `CancelRunService` for each one. A cancellable run is a JobRun with status of any of the following: 

```
PENDING
QUEUED
WAITING_ON_CONNECTIONS
PREPROCESSING
STARTED
```

The response body should be an array of all the cancelled run IDs.

### Describe alternate solutions

N/A

<sub>[TRI-1367](https://linear.app/triggerdotdev/issue/TRI-1367/feat-allow-cancelling-all-job-runs-for-a-given-event-id)</sub>

**Comment by Arbtrage** [comment]
Hi @ericallam , I would like to work on this issue .

**Comment by abhishek-nigam** [comment]
Hi @ericallam I'd like to work on this. Though, I have experience working with JS, TypeScript is new to me. I hope by working through this I'll learn about it, as well as make my first open source contribution! Shall I take a stab at it?
