### ISSUE TITLE
[TRI-1377] Throwing a string from inside runTask doesn't bubble up properly to the run

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#582]
If you do this inside of run, the run fails (which is correct) but you get "Unknown error" on the run.

```ts
await io.runTask(
    "a-task",
    async () => {
       throw "Shopify Order not found";
    },
);
```

It works properly if you do `throw new Error("Shopify Order not found");`

<sub>[TRI-1377](https://linear.app/triggerdotdev/issue/TRI-1377/throwing-a-string-from-inside-runtask-doesnt-bubble-up-properly-to-the)</sub>

**Comment by martinse** [comment]
The same issue if throwing custom objects, e.g. `throw {"something": "custom"};`

**Comment by msk4862** [comment]
@matt-aitken I'm trying triage this issue, can you please help understand on how can I test the updated  `io.runTask` function in my local setup?
