### ISSUE TITLE
feat: ADD LICENSE SECTION TO README.MD

### ISSUE THREAD

**Issue by shelar1423** [triggerdotdev/trigger.dev#587]
### Is your feature request related to a problem? Please describe.

No,

### Describe the solution you'd like to see

Adding a License section to README.md file

### Describe alternate solutions

ADDING A HYPERLINK TEXT IN README TO REDIRECT TO LICENSE FILE

### Additional information

I would like to work on this issue , kindly assign me this

**Comment by nicktrn** [comment]
Hi @shelar1423 and thanks for your contribution! Sadly, we won't be accepting any unrequested changes to the README file for the time being.
