### ISSUE TITLE
feat: Adding Scroll to Top Button

### ISSUE THREAD

**Issue by Kritika30032002** [triggerdotdev/trigger.dev#596]
### Is your feature request related to a problem? Please describe.

Yes, It is difficult for user to come back to top after scrolling down too much.

### Describe the solution you'd like to see

Adding Scroll to Top Button

### Describe alternate solutions

NA

**Comment by Kritika30032002** [comment]
Assign me this

**Comment by nkrider7** [comment]
Hi, Can I Work this Task

**Comment by D-K-P** [comment]
Hi @Kritika30032002 this isn't a known issue so i am closing this issue.
