### ISSUE TITLE
[TRI-1395] Calling `sendEvent` with a duplicate ID and a `deliverAt` or `deliverAfter` option should update the existing event

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#604]
Currently calling `sendEvent` with a duplicate event ID doesn't update the event at all, but if the event hasn't been delivered yet (it has a delivery date in the future) we should update the events:

- payload
- context
- deliverAt

<sub>[TRI-1395](https://linear.app/triggerdotdev/issue/TRI-1395/calling-sendevent-with-a-duplicate-id-and-a-deliverat-or-deliverafter)</sub>

**Comment by ydv-ankit** [comment]
i want ot work on this issue

**Comment by ericallam** [comment]
@hmacr yea I think it makes sense to allow them to update the event so it can get delivered immediately if there is no `deliverAt` or `deliverAfter` in the duplicate request. And 👍 to the 5-second threshold idea

**Comment by hmacr** [comment]
@ericallam Cool! I have a working impl for this change, let me create a PR.
