### ISSUE TITLE
[TRI-1401] feat: Add support for tabler-icons when using the `icon` for Tasks

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#616]
## Problem

When you use `io.runTask` you can provide an `icon` in the options. (Docs: https://trigger.dev/docs/sdk/io/runtask).

This property is a string and we currently have support for:
- Some company names (used by our integrations), such as "github". This uses the `@trigger.dev/companyicons` package: https://github.com/triggerdotdev/companyicons
- Some internal icons (https://github.com/triggerdotdev/trigger.dev/blob/ebe78017efdf7bd53c0e4414a8302b7f0ff2648d/apps/webapp/app/components/primitives/NamedIcon.tsx#L73)

We want to add lots more icons, that are open source friendly. 

https://tabler-icons.io/ is the perfect fit for this.

## Solution

Add support for passing in a `tabler-icons` named to the `NamedIcon` component. Somewhere like here: https://github.com/triggerdotdev/trigger.dev/blob/ebe78017efdf7bd53c0e4414a8302b7f0ff2648d/apps/webapp/app/components/primitives/NamedIcon.tsx#L218

This means it would first try and render an internal icon, or a company icon. If they fail then it would render a tabler-icon.

There are so many icons in this set, we need to be careful how we accomplish this. I think the best way would be to use their sprite sheet, as it can be cached and tends to be efficient for rendering: https://github.com/tabler/tabler-icons#svg-sprite

## To test
1. Add an icon name from tabler-icons to this runTask in the catalog: https://github.com/triggerdotdev/trigger.dev/blob/ebe78017efdf7bd53c0e4414a8302b7f0ff2648d/references/job-catalog/src/events.ts#L26
2. Test that it comes through correctly
3. Test that "github" still works (that uses companyicons)

## Tasks
- [ ] Add support for tabler-icons
- [ ] Update the docs with a mention and link to tabler-icons instead of font-awesome

<sub>[TRI-1401](https://linear.app/triggerdotdev/issue/TRI-1401/feat-add-support-for-tabler-icons-when-using-the-icon-for-tasks)</sub>

**Comment by RamK777-stack** [comment]
@matt-aitken While running the task, I ran into an issue. it throws `TypeError: callback is not a function`

```

import { eventTrigger } from "@trigger.dev/sdk";
import { client } from "@/trigger";
import { z } from "zod";

// your first job
client.defineJob({
  id: "new person",
  name: "New person",
  version: "0.0.1",
  trigger: eventTrigger({
    name: "person",
    schema: z.object({
      name: z.string(),
      email: z.string(),
    }),
  }),
  run: async (payload, io, ctx) => {
    await io.logger.info("New person", { payload });

    await io.runTask("task-example-1", async () => {
      return {
        message: "Hello World",
      };
    });
  },
});

```

<img width="947" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/69167444/55f39cf3-85cc-433a-99dc-1608b608773e">


Do you have any idea about this? what I am missing !!

**Comment by ericallam** [comment]
@RamK777-stack which version of the SDK are you using?

**Comment by RamK777-stack** [comment]
@ericallam I am using version ` 2.2.0`

before started working on this issue I updated using `npx @trigger.dev/cli@latest update`

**Comment by chaturrved** [comment]
Hi @matt-aitken , pnpm install @tabler/icons and

```html
      <svg className={className}>
          <use xlinkHref=`{@tabler/tabler-sprite.svg#${name}}` />
      </svg>
``` 
does not seem to work.

- Copy the icon svg sprite file from Github tabler/tabler-icons into the folder  public/tabler/
- Use https://github.com/tabler/tabler-icons#svg-sprite
is this what you were going for?

```html
      <svg className={className}>
          <use xlinkHref={`/tabler/tabler-sprite.svg#${name}`} />
      </svg>
``` 
I am doing something like this now it works, is it ok?

And also should I write something similar to 

https://github.com/triggerdotdev/trigger.dev/blob/ebe78017efdf7bd53c0e4414a8302b7f0ff2648d/apps/webapp/app/components/primitives/NamedIcon.tsx#L203

to check if tabler has that particular icon?

**Comment by matt-aitken** [comment]
@chaturrved yes this is exactly what I was thinking, having the sprite file in our repo. 

Is it possible to write a `hasIcon` function for Tabler? Obviously it would be if you listed out every possible icon in a Set to look through, but do they have anything built-in to do that?

**Comment by chaturrved** [comment]
@matt-aitken no there isn't anything built in like hasIcon, we would have to do that's better option Or we can expect icon name to be "tabler-[ICON-NAME]" and those icons will be rendered from tabler, but this won't be able to guarantee icon exists in tabler.

**Comment by michalkow** [comment]
Maybe you could use their [tags.json](https://github.com/tabler/tabler-icons/blob/master/packages/icons/tags.json) file to write the function?

**Comment by chaturrved** [comment]
I did see that but thought don't need all those objects here just to only check if it exists. I just took the keys to prepare a set. I don't know what's better, both of these i.e. svg and object will have to be changed every time new icons are added.

**Comment by martinse** [comment]
Could another task to this issue be to add documentation on trigger.dev/docs on how/where to find available icons? Found this issue and the reference to `NamedIcon.tsx` to figure out what my currently available options were.

**Comment by matt-aitken** [comment]
@chaturrved I like how you did it 👍 

It's a bit of maintenance when we upgrade but I think that's ok given we're going for the sprite as we don't know which icons will be used.

This is now merged into main and will be deployed to cloud soon (probably early next week) 🥳 

@martinse generally I think I'd encourage people to use Tabler rather than our internal icon set we have in NamedIcon. But we don't do a good job of documenting [company icons](https://github.com/triggerdotdev/companyicons) at the moment. If you think that would be helpful definitely creating an issue for it and feel free to work on it you want 😄
