### ISSUE TITLE
feat: allow ngrok --domain

### ISSUE THREAD

**Issue by ericclemmons** [triggerdotdev/trigger.dev#621]
### Is your feature request related to a problem? Please describe.

In development for webhooks in various services, I have to go to each of them & update the URL with the new tunnel URL from `pnpm dlx @trigger.dev/cli@latest dev`.

ngrok allows for a single, free, dedicated hostname associated with your account.

I'd like Trigger to take advantage of this somehow.

### Describe the solution you'd like to see

Support ngrok's `--domain` flag:

```shell
ngrok http --domain=i-love-me-some-trigger.ngrok-free.app 3000
```

could be passed via:

```
pnpm dlx @trigger.dev/cli@latest dev --ngrok-domain=i-love-me-some-trigger.ngrok-free.app
```

### Describe alternate solutions

1. Have a flag like `dev --public-url=i-love-me-some-trigger.ngrok-free.app` that's not ngrok-specific. Internally, it'd be used by ngrok, but if it eventually became localtunnel.me or an alternative, the flag won't need deprecation.

1. If ngrok is already running, use the current URL instead of making a new tunnel:

	```js
	const fetch = require('node-fetch')
	const tunnelUrl = fetch('http://localhost:4040/api/tunnels')
	  .then(res => res.json())
	  .then(json => json.tunnels.find(tunnel => tunnel.proto === 'https'))
	  .then(secureTunnel => secureTunnel.public_url)
	  .catch(err => {
		// Tunnel like normal
	    return createTunnel(...);
	  })
	```
	
	(ngrok has a limit to 1 connection on the free tier)

	This would work seamlessly if someone has a custom `ngrok service`

3. It would be a tighter coupling with ngrok (risky!) and start a `trigger` tunnel (`ngrok start trigger` if there's an ngrok config for it – https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/.

4. Have a JS hook in `trigger.ts` for developers to programmatically update their other service APIs (through _those_ APIs) with the new URL.  This seems like a stupidly high level of friction TBH:

```js
new TriggerClient({
  onCreateTunnel({ url }) {
	// Update all backends with the new dev tunnel URL, assuming they have an API 🙏
  }
})
```

**Comment by matt-aitken** [comment]
Hi @ericclemmons, I think this issue should be solved by this PR which will get merged in the next few days: #597. It solves this issue: #590.

I'm going to close this as a duplicate, but let me know if you think this is a separate issue.
