### ISSUE TITLE
feat: adding icons to the frameworks section in docs

### ISSUE THREAD

**Issue by shelar1423** [triggerdotdev/trigger.dev#631]
###  Adding icons to the frameworks section in docs to make the look more enhanced 
![image](https://github.com/triggerdotdev/trigger.dev/assets/82649533/8c02e101-5c8c-4584-9697-55e26274bf2e)

### Describe the solution you'd like to see

searching for logo icons on font aswome and calling the class in the icon section of the file 

### Describe alternate solutions

if logo not found in font aswome we can find similar icons to the logo 

## i would like to work on this issue

**Comment by shelar1423** [comment]
@matt-aitken have a review and let me know

**Comment by matt-aitken** [comment]
Yep I like the idea of adding font awesome icons to these if you can find good ones 👍
