### ISSUE TITLE
feat: changing getting help icons

### ISSUE THREAD

**Issue by shelar1423** [triggerdotdev/trigger.dev#632]
### Is your feature request related to a problem? Please describe.

As twitter is now X ,the icon should be fixed and also other cards can aslo have a better icon
![image](https://github.com/triggerdotdev/trigger.dev/assets/82649533/f11298bd-5411-4bce-9173-8e561165510f)

### Describe the solution you'd like to see

changing icons for these cards and enhancing them with better icons for a more better look

### Describe alternate solutions

if not all twitter should be changed to X

## I WOULD LIKE TO WORK ON THIS ISSUE

**Comment by shelar1423** [comment]
@matt-aitken have a review and let me know

**Comment by matt-aitken** [comment]
@shelar1423 it would be good to change that Twitter icon to X. 

In general I think it would be good to stick with the font awesome icons so that we have consistency across the docs and it's faster to add news docs pages. So I'm happy for the other icons to change, but we should stick with font awesome, they have a massive catalogue: https://fontawesome.com/search?o=r&m=free

**Comment by shelar1423** [comment]
@matt-aitken so what do you suggest,shall I just change twitter ?

**Comment by shelar1423** [comment]
Yeah@matt-aitken surely,was wondering if this issue could be assigned diamonds and then assigned to me

**Comment by Smartmind12** [comment]
Hey @matt-aitken can you review this PR where i have updated the icons using font awesome!

**Comment by shelar1423** [comment]
Hey @Smartmind12 thanks but I'm already with conversation with @matt-aitken and working on this  issue .

**Comment by Smartmind12** [comment]
> Hey @Smartmind12 thanks but I'm already with conversation with @matt-aitken and working on this issue .

Hey @shelar1423 this is an open issue and any one can contribute to the repo and issues!

**Comment by shelar1423** [comment]
Hey @Smartmind12 sure let @matt-aitken assign it then it'll be clear .

**Comment by D-K-P** [comment]
Hey @shelar1423 @Smartmind12 - We’re not assigning issues, we’ll accept the best PR for an issue (not necessarily the first PR either). Triaging assignments during hacktoberfest doesn’t scale.

**Comment by Smartmind12** [comment]
> Hey @shelar1423 @Smartmind12 - We’re not assigning issues, we’ll accept the best PR for an issue (not necessarily the first PR either). Triaging assignments during hacktoberfest doesn’t scale.

Hey @D-K-P I am aware of that and hence added my PR as a submission for review!
