### ISSUE TITLE
[TRI-1414] Ability to delete a Project

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#638]
You can't delete a Project from the UI at the moment.

## Considerations
By deleting a project that has Jobs that are deployed to Staging or Prod, it will break user's apps.
- Indexing their Jobs will fail because the API keys won't exist anymore
- They won't be sent any events to Trigger Jobs
- All API and SDK calls will fail for that deleted Project

We need to make sure that users are fully aware of what will happen if they choose to delete it. That should include showing them what will be impacted, e.g. a list of Jobs with the environments that they're active in, and the number of runs they've had in the past week.

We could also have soft-deleting (i.e. archiving) as the first step. This would have the same impact as deleting except the data would still exist (with an archived flag). These would live in the UI and could be fully deleted from there, and automatically deleted after being in the archive for a certain period.

<sub>[TRI-1414](https://linear.app/triggerdotdev/issue/TRI-1414/ability-to-delete-a-project)</sub>

**Comment by Abhi1992002** [comment]
@matt-aitken can i work on it?

**Comment by Abhi1992002** [comment]
i could do archive functionality easily but not able to understand "How to delete it after 30 days?"

> should i use setInterval or setTimeout? (may create use)
> or to run a job everyday and delete all those project which are archived and have isArchivedTime greater than 30 (using some external libraries)?

**Comment by madhukaraman** [comment]
Hey @matt-aitken can i pick this issue?
