### ISSUE TITLE
feat: inconsistent use of image tags in docs

### ISSUE THREAD

**Issue by nabinbhatt** [triggerdotdev/trigger.dev#640]
### Is your feature request related to a problem? Please describe.

Some pictures use markdown tags, and some use iframe tags. Because of this, the images look different—some have rounded corners, and some don't.

### Describe the solution you'd like to see

All images should consistently use the iframe tag to maintain a uniform appearance.

### Describe alternate solutions

If using both markdown and iframe tags is essential, styling should be applied consistently to maintain a uniform appearance.

### Additional information

Using markdown tag
![image](https://github.com/triggerdotdev/trigger.dev/assets/83168881/d81c4d65-6148-4b94-ae33-8f32b4c5f1b1)
Using iframe tag
![image](https://github.com/triggerdotdev/trigger.dev/assets/83168881/0261359a-d1fd-4c5c-b151-6b9080a191d7)

**Comment by Dv04** [comment]
Hey can I take this issue?

**Comment by nabinbhatt** [comment]
Hey @Dv04 I am already working on this issue

**Comment by Dv04** [comment]
Oh alright, no worries.

**Comment by matt-aitken** [comment]
Could you provide a link to the page with that iframe tag image? I think the rules for images should be
- Use markdown syntax wherever possible because it's easier to write
- Use Mintlify's image frames when you want to add a caption (which I think is what's happening in the second example above). Mintlify's docs: https://mintlify.com/docs/content/components/frame

**Comment by nabinbhatt** [comment]
Here it is: https://trigger.dev/docs/documentation/guides/self-hosting/supabase

I think we can use frames even if we don't need caption, this page have images without caption and using frames.

**Comment by nabinbhatt** [comment]
Since other elements also have rounded corners, it will make the documentation look better.
![image](https://github.com/triggerdotdev/trigger.dev/assets/83168881/327b8e56-27bd-4072-8491-adefa13ddd44)

**Comment by samejr** [comment]
Hey @nabinbhatt i've just reviewed this issue and although it would be nice for visual consistency to use the Frame component, it won't be as flexible when we need to copy paste documentation into different GitHub repos and vice versa, which we do quite often. So keeping it as close to Markdown as possible is preferred.

Im going to close this issue, but this is definitely a nice suggestion so please do suggest more like this if you spot them. 👍

**Comment by nabinbhatt** [comment]
Alright, thanks for the clarification.
