### ISSUE TITLE
bug: pagination error in job-run page

### ISSUE THREAD

**Issue by hmacr** [triggerdotdev/trigger.dev#641]
### Provide environment information

System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 66.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 7.18.1 - ~/.nvm/versions/node/v18.15.0/bin/pnpm

### Describe the bug

Pagination in the Job Runs page doesn't work as expected.

When we navigate between the pages using `next` and `prev`, and finally end up on the initial page, it still shows the `prev` button. This shouldn't be shown since it is the first page of the run list.
Also, when this `prev` button is clicked, it shows a page with just the first run item and no more `prev`/`next` buttons to navigate.

https://github.com/triggerdotdev/trigger.dev/assets/132386067/5711f1c2-6fda-4d92-8521-27cb27f5bc10

### Reproduction repo

none

### To reproduce

1. Create a job with more than 20 job runs.
2. Go to the job run page and navigate between the pages.

**Comment by matt-aitken** [comment]
@hmacr I've experienced this as well. It'd be great to fix it

**Comment by hmacr** [comment]
@matt-aitken Cool! I just created a PR 😊
