### ISSUE TITLE
feat: add icons to the guides/platforms section in docs

### ISSUE THREAD

**Issue by nabinbhatt** [triggerdotdev/trigger.dev#644]
### Is your feature request related to a problem? Please describe.

We can add icons to the platforms section in docs to make it visually appealing.

![image](https://github.com/triggerdotdev/trigger.dev/assets/83168881/988887f2-61a4-44df-ad89-06114feac707)

### Describe the solution you'd like to see

Add icons from fontawesome library

### Describe alternate solutions

the above solution might work

### Additional information

I would like to work on this issue. Please take a look and let me know. Thanks

**Comment by lalitkumawat1m** [comment]
Want to work on this issue please assign to me under Hactoberfest label

**Comment by nabinbhatt** [comment]
Hey @lalitkumawat1m can you see the additional information section above?

**Comment by lalitkumawat1m** [comment]
Yes

**Comment by nabinbhatt** [comment]
@lalitkumawat1m please find other open issues as I am ready to work on this one.

**Comment by nabinbhatt** [comment]
Hi, @matt-aitken could you please review and let me know
