### ISSUE TITLE
[TRI-1424] Add a CLI init warning that we don't support long-running servers

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#655]
When you run `npx @trigger.dev/cli@latest init` it sets your project up for you (if we support your framework).

At the end it spits out some advice.

We should show a warning here that we don't currently support long-running servers. With a link to this issue: https://github.com/triggerdotdev/trigger.dev/issues/244

It would be added after "✔ Successfully initialized Trigger.dev!" and before the "Next steps:", in the `printNextSteps` function.

<sub>[TRI-1424](https://linear.app/triggerdotdev/issue/TRI-1424/add-a-cli-init-warning-that-we-dont-support-long-running-servers)</sub>

**Comment by Asymtode712** [comment]
I want to work on it. Please assign me

**Comment by vineetjk** [comment]
@matt-aitken I have created a PR, please review it
Thanks :)
