### ISSUE TITLE
[TRI-1425] Improve the Plain integration documentation

### ISSUE THREAD

**Issue by D-K-P** [triggerdotdev/trigger.dev#657]
## Overview:

Update the [Plain integration documentation](https://trigger.dev/docs/integrations/apis/plain) so it is much easier to use as a reference.

We have just overhauled our [GitHub documentation](https://trigger.dev/docs/integrations/apis/github) and would like all of the rest of our integrations to follow the same structure.

*Please use the references and resources at the bottom of this post to complete this issue.*

### Plain overview & authentication:

This page is currently [this](https://trigger.dev/docs/integrations/apis/plain).

* **Page Title:** Plain overview & authentication
* **Sidebar title:** Overview & authentication
* **Page content**: authentication with Plain, in the same format as this: [https://trigger.dev/docs/integrations/apis/github](https://trigger.dev/docs/integrations/apis/github)

### Plain Tasks:

* **Page title:** Plain tasks
* **Sidebar title:** Tasks
* **Page content:** all the tasks available from our Plain integration, in the same format as this: [https://trigger.dev/docs/integrations/apis/github-tasks](https://trigger.dev/docs/integrations/apis/github-tasks). Also include one example at the bottom with clear comments. See references below for sample code.

### References & resources:

* Our current [Plain documentation](https://github.com/triggerdotdev/trigger.dev/blob/main/docs/integrations/apis/plain.mdx) in the GitHub repo.
* Example job code to use - [job catalog](https://github.com/triggerdotdev/trigger.dev/blob/main/references/job-catalog/src/plain.ts) and [jobs showcase](https://trigger.dev/showcase/jobs/plainUpdateCustomer).
* We use Mintlify for our docs, [documentation here](https://mintlify.com/docs/quickstart)

> \[!IMPORTANT\]
> Please include screenshots of the pages when you submit a PR for us to check

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1425](https://linear.app/triggerdotdev/issue/TRI-1425/improve-the-plain-integration-documentation)</sub>

**Comment by vishnugaruda246** [comment]
@D-K-P can you assign me to the issue , would like to work on it
