### ISSUE TITLE
[TRI-1431] Improve the Airtable integration documentation

### ISSUE THREAD

**Issue by D-K-P** [triggerdotdev/trigger.dev#665]
## Overview:

Update the [Airtable integration documentation](https://trigger.dev/docs/integrations/apis/airtable) so it is much easier to use as a reference.

We have just overhauled our [GitHub documentation](https://trigger.dev/docs/integrations/apis/github) and would like all of the rest of our integrations to follow the same structure.

*Please use the references and resources at the bottom of this post to complete this issue.*

### Airtable overview & authentication:

This page is currently [this](https://trigger.dev/docs/integrations/apis/airtable).

* **Page Title:** Airtable overview & authentication
* **Sidebar title:** Overview & authentication
* **Page content**: authentication with Airtable, in the same format as [this](https://trigger.dev/docs/integrations/apis/github). If there is no overview, write one. You can use their company website for inspiration.

### Airtable Tasks:

* **Page title:** Airtable tasks
* **Sidebar title:** Tasks
* **Page content:** all the tasks available from our Airtable integration, in the same format as this: [https://trigger.dev/docs/integrations/apis/github-tasks](https://trigger.dev/docs/integrations/apis/github-tasks). Please include code comments in all of the code examples. Also include one example at the bottom with clear comments. See references below for sample code.

### References & resources:

* [GitHub documentation](https://trigger.dev/docs/integrations/apis/github) to reference
* Our current [Airtable documentation](https://github.com/triggerdotdev/trigger.dev/blob/main/docs/integrations/apis/airtable.mdx) in the GitHub repo.
* Example job code to use - [job catalog](https://github.com/triggerdotdev/trigger.dev/blob/main/references/job-catalog/src/airtable.ts) and [jobs showcase](https://trigger.dev/showcase?tags=&integrations=airtable).
* We use Mintlify for our docs, [documentation here](https://mintlify.com/docs/quickstart)

> \[!IMPORTANT\]
> Please include a video or screenshots of the pages when you submit a PR for us to check

<sub>[TRI-1431](https://linear.app/triggerdotdev/issue/TRI-1431/improve-the-airtable-integration-documentation)</sub>

**Comment by D-K-P** [comment]
Hey @shelar1423 looking good, a few tasks:

### Overview
- Could you change the overview to this: "Our Airtable integration allows you to easily connect to the Airtable API and perform tasks such as creating/updating/deleting single or multiple records in your tables.

For examples of some of the things you can do with it, check out our Jobs Showcase:"

### Tasks:
- Could you please add 'Example usage' with a job to the bottom of the tasks page please, you can use the example here: https://trigger.dev/docs/integrations/apis/airtable
- Also for all of the examples, you don't need to add 'const =' for any of them (same as GitHub tasks).
- Could you also format them so that they aren't really long horizontally. You can use multiple lines (again see GitHub). 
Thanks!

**Comment by shelar1423** [comment]
@D-K-P sure

**Comment by shelar1423** [comment]
@D-K-P did not understand the "const=" part which u mentioned, shall i remove the const = from the code what do you want me to do im a bit confused as even github tasks have some const= 
![image](https://github.com/triggerdotdev/trigger.dev/assets/82649533/c6e85da8-f934-4409-8c04-03870e030b19)
