### ISSUE TITLE
Supabase Integration

### ISSUE THREAD

**Issue by liweihan** [triggerdotdev/trigger.dev#67]
Hi, I see you guys have a example of using supabase trigger at your home page. Just wondering if you have a example code or  supabase integration coming? 

Thanks!

**Comment by ericallam** [comment]
We don't have an official integration for Supabase yet but you can use our generic webhook trigger, I've put together an example here: https://github.com/triggerdotdev/trigger.dev-examples/blob/main/src/examples/supabase-hooks.ts.

After you get that example running head over to your dashboard and you should see the webhook URL:

![CleanShot_2023-02-02_at_20 58 21](https://user-images.githubusercontent.com/534/220573330-0c641667-bfb9-49de-b6fd-77e10ab16188.png)

Head over to Supabase and enable their webhooks feature if you haven't already:

![CleanShot_2023-02-02_at_20 58 31](https://user-images.githubusercontent.com/534/220573410-4e2952ba-6ad8-4eef-b36c-d56cbfcb36c9.png)

Then fill out the form like so. In the example I have a users table and I'm going to listen to all three events:

![CleanShot_2023-02-02_at_20 59 45](https://user-images.githubusercontent.com/534/220573498-91dc27d3-c707-477b-b8e6-9638bbf911cf.png)

Make sure the request is a POST request.

**Comment by liweihan** [comment]
Thanks, I can close it for now
