### ISSUE TITLE
[TRI-1444] Only allow logins from whitelisted_emails (for self-hosting)

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#685]
Currently there isn't a convenient way to lock down logins to a self-hosted Trigger.dev service.

We should add a new ENV var which allows a regex pattern to be used to only allow certain emails.

```
WHITELISTED_EMAILS="matt@gmail\.com|jane@yahoo\.com"
```

Only emails that match this would be able to sign-up or login.

It must be added to `env.server.ts` file, and it needs to be optional. Probably the easiest way to implement this would be to modify the `findOrCreateUser()` function in `user.server.ts` to first check the whitelist if it exists and just throw an error.

<sub>[TRI-1444](https://linear.app/triggerdotdev/issue/TRI-1444/only-allow-logins-from-whitelisted-emails-for-self-hosting)</sub>

**Comment by eweremono** [comment]
I think it could be from whitelisted, TLDs too not just emails, so that it can cover for an organization

**Comment by nicktrn** [comment]
> TLDs too not just emails

regex will cover this

**Comment by vineetjk** [comment]
I would like to give it a try

**Comment by nicktrn** [comment]
No need to ask for permission, feel free to give it a go!

**Comment by AsbarK** [comment]
#692

**Comment by AsbarK** [comment]
#692

**Comment by AsbarK** [comment]
hey @nicktrn can you review my pr
