### ISSUE TITLE
feat: Add labels to the readme

### ISSUE THREAD

**Issue by shraddha761** [triggerdotdev/trigger.dev#695]
### Is your feature request related to a problem? Please describe.

I think the label in the readme makes it more attractive 

### Describe the solution you'd like to see

Assign this issue to me so that i can add label to the readme

### Describe alternate solutions

Nope

**Comment by nicktrn** [comment]
Hi @shraddha761 and thanks for your contribution! Sadly, we won't be accepting any unrequested changes to the README file for the time being.
