### ISSUE TITLE
feat: DarkMode button

### ISSUE THREAD

**Issue by shraddha761** [triggerdotdev/trigger.dev#703]
### Is your feature request related to a problem? Please describe.

There should be dark mode button in website which toggle light and dark

### Describe the solution you'd like to see

Change theme of website

### Describe alternate solutions

Assign this issue to me

**Comment by CryptoGuyDev** [comment]
Assign this issue to me

**Comment by D-K-P** [comment]
Hey @shraddha761, @CryptoGuyDev we don't have a light mode and aren't planning on adding it any time soon, so don't need this toggle added.

**Comment by smm-h** [comment]
Not having a light mode and not willing to even consider it made me delete my account. Hope this changes.
