### ISSUE TITLE
feat: Sitemap.xml

### ISSUE THREAD

**Issue by Killer2OP** [triggerdotdev/trigger.dev#704]
###  feature request 

A sitemap is a file that lists all the pages of a website, helping search engines understand its structure and content.

### Describe the solution you'd like to see

It enhances search engine optimization (SEO) efforts by improving website visibility and indexing. I believe adding sitemap would be a perfect addition to this project.

**Comment by nicktrn** [comment]
Thanks, but the only place a sitemap would be useful in this repo is the Webapp, which doesn't really have any public routes we need to announce for indexing.
