### ISSUE TITLE
Bug: `cannot read properties of undefined (reading: defaultQuery)` in OpenAI integration

### ISSUE THREAD

**Issue by shricodev** [triggerdotdev/trigger.dev#723]
### Provide environment information

  ```bash
  System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 4.67 GB / 15.73 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.CMD
```

### Describe the bug

When trying to register a job using OpenAI specific it throws an error with `cannot read properties of undefined (reading: defaultQuery)`

![openai_error_trigger](https://github.com/triggerdotdev/trigger.dev/assets/76906722/6d2d938a-fbd3-47e4-b85b-e3beecafe259)

This is the exact job file that uses OpenAI integration: https://github.com/shricodev/blog-resume-builder/blob/e53603127225a7ceed156a3b8235bd2d9caed817/jobs/openAIClient.ts

### Reproduction repo

https://github.com/shricodev/blog-resume-builder/tree/e53603127225a7ceed156a3b8235bd2d9caed817

### To reproduce

- Clone the repo in this committed state: https://github.com/shricodev/blog-resume-builder/tree/e53603127225a7ceed156a3b8235bd2d9caed817
- Setup `.env.local` with the API keys
- Run the dev server along with `npx @trigger.dev/cli@latest dev`
- In the Jobs section in the Trigger dashboard, run the job `jobs\openAIClient.ts` and that should trigger the error.

### Additional information

I tried checking if the error is on any other integrations and not just the OpenAI integrations but the Slack integration seems to work fine.

![Screenshot 2023-11-05 132151](https://github.com/triggerdotdev/trigger.dev/assets/76906722/331032ee-55e3-4f96-9c10-a7e56deba88f)

**Comment by matt-aitken** [comment]
This will be fixed in the next release.

You can use `io.openai.chat.completions.backgroundCreate` instead which is the newer way of doing this and shouldn't have the same issue.
