### ISSUE TITLE
bug: TypeScript type reduced to 'never' (GitHub integration)

### ISSUE THREAD

**Issue by jaaneh** [triggerdotdev/trigger.dev#740]
### Provide environment information

System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 6.85 GB / 9.71 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.4 - ~/.local/share/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun

### Describe the bug

Trying to use the GitHub integration and saw this error appear.  This happens when trying to access anything on the issue property.

![image](https://github.com/triggerdotdev/trigger.dev/assets/27323317/66c873af-f7dc-4751-9b67-613abbf0b5df)

```
Property 'number' does not exist on type 'never'.
  The intersection 'Issue & { state: "open"; closed_at: null; }' was reduced to 'never' because property 'closed_at' has conflicting types in some constituents.
  ```

### Reproduction repo

N/A

### To reproduce

Create a new job with a GitHub integration, and attempt to use a method that relies on Issue type.

**Comment by nicktrn** [comment]
Thanks for reporting this!

Your tsconfig needs to have `strict` or at the very least `strictNullChecks` enabled for types to work as they should. They come straight from Octokit.

Reproduction:

- Fails with `strictNullChecks` [disabled](https://www.typescriptlang.org/play?strictNullChecks=false#code/JYOwLgpgTgZghgYwgAgJIGd0FcLoPIAOEIEAJgKIBuxYyA3gFDLLCY4BcabKAZPU82TowcSJwBEAeyIhxAbgHMEAG0noyAfVGcQWZcoXMAvgqMMGoSLEQoM2FI2a6AtgCNoOrG+iGhIyAD8EtLE4sgAPsjiKmpk8gIx6qRaYJzCUKAA5hHIuvqm5giSIMIs3ITEZMgAvPRGyHDoXPb4MmRUNOas9hUkpAB03Tj9Lu5QQA)
- Works with `strictNullChecks` [enabled](https://www.typescriptlang.org/play?strictNullChecks=true#code/JYOwLgpgTgZghgYwgAgJIGd0FcLoPIAOEIEAJgKIBuxYyA3gFDLLCY4BcabKAZPU82TowcSJwBEAeyIhxAbgHMEAG0noyAfVGcQWZcoXMAvgqMMGoSLEQoM2FI2a6AtgCNoOrG+iGhIyAD8EtLE4sgAPsjiKmpk8gIx6qRaYJzCUKAA5hHIuvqm5giSIMIs3ITEZMgAvPRGyHDoXPb4MmRUNOas9hUkpAB03Tj9Lu5QQA)

**Comment by jaaneh** [comment]
> Thanks for reporting this!
> 
> Your tsconfig needs to have `strict` or at the very least `strictNullChecks` enabled for types to work as they should. They come straight from Octokit.
> 
> Reproduction:
> 
> * Fails with `strictNullChecks` [disabled](https://www.typescriptlang.org/play?strictNullChecks=false#code/JYOwLgpgTgZghgYwgAgJIGd0FcLoPIAOEIEAJgKIBuxYyA3gFDLLCY4BcabKAZPU82TowcSJwBEAeyIhxAbgHMEAG0noyAfVGcQWZcoXMAvgqMMGoSLEQoM2FI2a6AtgCNoOrG+iGhIyAD8EtLE4sgAPsjiKmpk8gIx6qRaYJzCUKAA5hHIuvqm5giSIMIs3ITEZMgAvPRGyHDoXPb4MmRUNOas9hUkpAB03Tj9Lu5QQA)
> * Works with `strictNullChecks` [enabled](https://www.typescriptlang.org/play?strictNullChecks=true#code/JYOwLgpgTgZghgYwgAgJIGd0FcLoPIAOEIEAJgKIBuxYyA3gFDLLCY4BcabKAZPU82TowcSJwBEAeyIhxAbgHMEAG0noyAfVGcQWZcoXMAvgqMMGoSLEQoM2FI2a6AtgCNoOrG+iGhIyAD8EtLE4sgAPsjiKmpk8gIx6qRaYJzCUKAA5hHIuvqm5giSIMIs3ITEZMgAvPRGyHDoXPb4MmRUNOas9hUkpAB03Tj9Lu5QQA)

Ah, that did it! Yeah, I had `stricky: true` but `strictNullChecks: false`. Flipping that did the job 🎉
