### ISSUE TITLE
[TRI-1642] Add Stripe invoice triggers

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#747]
## How to add a new trigger

1. Add an event specification for each: https://github.com/triggerdotdev/trigger.dev/blob/main/integrations/stripe/src/events.ts
2. Add a function for each, referencing the event: https://github.com/triggerdotdev/trigger.dev/blob/131d0dbea420b3174f6a6ea11de1fbb844853d91/integrations/stripe/src/index.ts#L848
3. Test the trigger works by adding it to the job-catalog, running it and triggering a webhook using Stripe's CLI: https://github.com/triggerdotdev/trigger.dev/blob/131d0dbea420b3174f6a6ea11de1fbb844853d91/references/job-catalog/src/stripe.ts#L165

## List of events to add:
**invoice.created**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever a new invoice is created. To learn how webhooks can be used with this event, and how they can affect it, see [Using Webhooks with Subscriptions](https://stripe.com/docs/subscriptions/webhooks).

**invoice.deleted**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever a draft invoice is deleted.

**invoice.finalization_failed**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever a draft invoice cannot be finalized. See the invoice’s [last finalization error](https://stripe.com/docs/api/invoices/object#invoice_object-last_finalization_error) for details.

**invoice.finalized**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever a draft invoice is finalized and updated to be an open invoice.

**invoice.marked_uncollectible**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice is marked uncollectible.

**invoice.paid**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice payment attempt succeeds or an invoice is marked as paid out-of-band.

**invoice.payment_action_required**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice payment attempt requires further user action to complete.

**invoice.payment_failed**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice payment attempt fails, due either to a declined payment or to the lack of a stored payment method.

**invoice.payment_succeeded**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice payment attempt succeeds.

**invoice.sent**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice email is sent out.

**invoice.upcoming**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs X number of days before a subscription is scheduled to create an invoice that is automatically charged—where X is determined by your [subscriptions settings](https://dashboard.stripe.com/account/billing/automatic). Note: The received Invoice object will not have an invoice ID.

**invoice.updated**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice changes (e.g., the invoice amount).

**invoice.voided**
data.object is an[ invoice](https://stripe.com/docs/api/events/types#invoice_object)
Occurs whenever an invoice is voided.

**invoiceitem.created**
data.object is an[ invoiceitem](https://stripe.com/docs/api/events/types#invoiceitem_object)
Occurs whenever an invoice item is created.

**invoiceitem.deleted**
data.object is an[ invoiceitem](https://stripe.com/docs/api/events/types#invoiceitem_object)
Occurs whenever an invoice item is deleted.

<sub>[TRI-1642](https://linear.app/triggerdotdev/issue/TRI-1642/add-stripe-invoice-triggers)</sub>

**Comment by D-K-P** [comment]
Assigned @rishi-raj-jain

**Comment by matt-aitken** [comment]
This was completed by @ericallam
