### ISSUE TITLE
[TRI-1655] Ability to cancel all runs for a Job (from SDK)

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#756]
Something like: `client.cancelRunsForJob('<you_job_id>')`

It would behave like `cancelRunsForEvent` in what would happen to the runs.

<sub>[TRI-1655](https://linear.app/triggerdotdev/issue/TRI-1655/ability-to-cancel-all-runs-for-a-job-from-sdk)</sub>

**Comment by SjxSubham** [comment]
@matt-aitken will u pls explain me this issue a little bit more ... so that i can try to solve it
