### ISSUE TITLE
Shopify webhook  - Failed sha256 verification

### ISSUE THREAD

**Issue by jaaneh** [triggerdotdev/trigger.dev#769]
I opened this originally in discussions, but unsure if this is better suited as an issue so re-opening it here. Feel free to close one and continue conversation in the other. Discussion https://github.com/triggerdotdev/trigger.dev/discussions/768

---

Hey there,

I've been trying to get up an going with the Shopify integration, however every time I trigger an event through Shopify it leads to a "Failed sha256 verification" error.

![image](https://github.com/triggerdotdev/trigger.dev/assets/27323317/d5924c04-9cd4-4822-a9a4-961f20e54fa2)

The webhook succeeds obviously when using the test event in Trigger, and it returns the payload (using the example below). I have set up webhook in Shopify, and I am also using the correct secrets/env vars.

I am self-hosting Trigger, and have input the DEV URL to Shopify as the app is not hosted yet.

Seeing as Shopify doesn't have a way to insert the secret that Trigger gives you, and they instead give us one, I assume Trigger registers this automatically when registering the trigger? Still, with the correct URL set in Shopify it fails to verify.

Here's an example piece of code that doesn't work:

```ts
import "@shopify/shopify-api/adapters/node"
import { Shopify } from "@trigger.dev/shopify"
import { client } from "../"

const shopify = new Shopify({
  id: "shopify",
  apiKey: process.env.SHOPIFY_API_KEY!,
  apiSecretKey: process.env.SHOPIFY_API_SECRET_KEY!,
  adminAccessToken: process.env.SHOPIFY_ADMIN_ACCESS_TOKEN!,
  hostName: process.env.SHOPIFY_SHOP_DOMAIN!
})

client.defineJob({
  id: "shopify/on-order-created",
  name: "Shopify: On Order Created",
  version: "0.1.0",
  trigger: shopify.on("orders/create"),
  run: async (payload, io, ctx) => {
    return { payload }
  }
})
```

**Comment by jaaneh** [comment]
Hi @nicktrn. Appreciate the reply.

I am running `2.2.10` on the SDK, Express and Shopify packages. The self-hosted is also on the latest `2.2.17`.

I've made sure the `apiSecretKey` is correct and matches. Please see below:

![image](https://github.com/triggerdotdev/trigger.dev/assets/27323317/21d8aff5-6789-467a-b5ce-6a3de8e90e42)
![image](https://github.com/triggerdotdev/trigger.dev/assets/27323317/30f1aede-4384-4fcb-9abe-00834f0af03d)

I've also tried to re-register it, by appending `-dev`

![image](https://github.com/triggerdotdev/trigger.dev/assets/27323317/5418ef20-38bb-43b6-b766-8eba49bdc97d)

... but it seems to still fail the verification.

![image](https://github.com/triggerdotdev/trigger.dev/assets/27323317/5fe6d2e2-228b-40d1-a7eb-ef4955eafb7d)

Here is the full code to my app.ts.
```ts
import express from "express"
import morgan from "morgan"

import { notFound, errorHandler } from "./handlers"

// Trigger
import "./trigger/jobs/shopify"
import { client } from "./trigger"
import { createMiddleware } from "@trigger.dev/express"

const app = express()

app.use(morgan("dev"))
app.use(express.json())
app.use(createMiddleware(client))

app.get("/", (_, res) => res.status(200).send({ status: "ok" }))

app.use(notFound)
app.use(errorHandler)

export default app
```

This is running the exact same job code as the example I gave above

**Comment by nicktrn** [comment]
Thanks for the detailed walkthrough!

No need to be embarrassed, it's not immediately clear why this wouldn't work.

It's essentially due to requests from the platform not all having a json `Content-Type`. If that parser middleware runs before our client middleware, it will consume the body stream and set `req.body = {}` for non-JSON cases.

That being said, we should document this - don't think there's a workaround apart from adding middlewares that mutate the request only *after* the client middleware.
