### ISSUE TITLE
require esm error

### ISSUE THREAD

**Issue by gutenye** [triggerdotdev/trigger.dev#78]
Follow the steps

1. npx create-trigger@latest blank-starter
1. yarn
2. yarn build
3. yarn start

And I got

```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/terminal-link/index.js from /node_modules/@trigger.dev/sdk/dist/index.js not supported.
```

**Comment by ericallam** [comment]
Thanks for the report @gutenye! Going to work on getting a fix released for this ASAP, sorry about this!

**Comment by ericallam** [comment]
This has been fixed in https://github.com/triggerdotdev/trigger.dev/commit/0b67b51ae4603a3a6b38dd1de4bc605554dcfb4c but don't think this will be released and fixed until tomorrow. Will keep this issue updated when it is fixed.

**Comment by gutenye** [comment]
Thanks for the quick fix.
