### ISSUE TITLE
How to deploy to render.com?

### ISSUE THREAD

**Issue by gutenye** [triggerdotdev/trigger.dev#79]
Hey Trigger team

I'm deploying to Render web service, and deploy to Render failed because it will do a health check (returns 2xx status for success) when deploying, since Trigger doesn't listen on any port, the check will always fail. You can read more [here](https://render.com/docs/deploys#zero-downtime-deploys) and you can't [disable the health check](https://community.render.com/t/how-can-i-disable-the-health-check-in-render/8526).

Thanks

**Comment by ericallam** [comment]
We currently don't support deploying to Render.com using their web services, only Background Workers. Check out our guide for more on deploying to Render here: https://docs.trigger.dev/guides/renderdotcom

**Comment by ericallam** [comment]
We're actually pretty close to adding the ability to deploy a hosted repository using a Render.com like experience, but through Trigger.dev (and 1 hosted repo included in our $25 a month plan). We'll be opening it up to as a Technology Preview this week where you will be able to try it out for free. Want me to let you know when it's available?

**Comment by gutenye** [comment]
Yes, definitely.
