### ISSUE TITLE
[TRI-1743] Look into using bore instead of ngrok for local tunnelling

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#790]
https://github.com/ekzhang/bore

<sub>[TRI-1743](https://linear.app/triggerdotdev/issue/TRI-1743/look-into-using-bore-instead-of-ngrok-for-local-tunnelling)</sub>

**Comment by matt-aitken** [comment]
Closing this because we created out own tunnel, Yet Another Local Tunnel (YALT)
