### ISSUE TITLE
bug: tests not running in isolation

### ISSUE THREAD

**Issue by sambarfoot** [triggerdotdev/trigger.dev#792]
### Provide environment information

System:
    OS: Linux 6.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (10) arm64 unknown
    Memory: 4.29 GB / 7.76 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/local/share/nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.1.0 - /usr/local/share/nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.10.5 - /usr/local/share/nvm/versions/node/v20.9.0/bin/pnpm

### Describe the bug

When using the testing package, mocked tasks are not reset and carry their value from the first declaration. 

### Reproduction repo

*

### To reproduce

Below are two example tests where the task sum should return a number.

```ts
import { createJobTester, toHaveSucceeded } from "@trigger.dev/testing";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

expect.extend({ toHaveSucceeded });
const testJob = createJobTester(vi);

describe("test 1", () => {
  it("input date is rounded to the hour", async () => {
    ....

    const testRun = await testJob(history, {
      payload: {
        debug: true,
      },
      tasks: {
        sum: 4
      }
    });
  
    // job run was successful
    expect(testRun).toHaveSucceeded();
    // check output
    expect(testRun.output.message).toEqual('4');
  });

it("test 2", async () => {
    ....

    const testRun = await testJob(history, {
      payload: {
        debug: true
      },
      tasks: {
        sum: 5
      }
    });
    // job run was successful
    expect(testRun).toHaveSucceeded();
    // check output
    expect(testRun.output.message).toEqual('5');
  });
});
```

When you run the test, the output of the test 2 is 4, upon further debugging you find that the output of the sum task is 4 not 5 for test 2.

**Comment by sambarfoot** [comment]
thank you @nicktrn

**Comment by nicktrn** [comment]
No worries, thanks for reporting! Package release shortly.
