### ISSUE TITLE
feat: Read more files in ENV_FILES_FALLBACK

### ISSUE THREAD

**Issue by Kalmarv** [triggerdotdev/trigger.dev#808]
### Is your feature request related to a problem? Please describe.

I'm currently trying to setup the self hosted version of trigger.dev with a Next.js docker standalone site. Environment variables in Next.js + Docker are notoriously difficult, so I have a setup utilizing env.development and env.production files.

Going through the initial setup of trigger.dev I've gotten to the point of running `npx @trigger.dev/cli@latest dev` to set everything up, but I kept getting the error `You must add TRIGGER_API_KEY to your .env file or set as runtime environment variable.`

Looking through the source of trigger.dev, I found in [readEnvVariables.ts](https://github.com/triggerdotdev/trigger.dev/blob/03703af682ab452a57a0c0e21e7b829eda564d4e/packages/cli/src/utils/readEnvVariables.ts#L5) it's not reading from the env.development and env.production files.

### Describe the solution you'd like to see

update [readEnvVariables.ts](https://github.com/triggerdotdev/trigger.dev/blob/03703af682ab452a57a0c0e21e7b829eda564d4e/packages/cli/src/utils/readEnvVariables.ts#L5) from

```typescript
const ENV_FILES_FALLBACK = [".env", ".env.local", ".env.development.local"];
```

to be

```typescript
const ENV_FILES_FALLBACK = [".env", ".env.local", ".env.development.local", ".env.development", ".env.production"];
```

### Describe alternate solutions

Change how I setup and use environment variables.

**Comment by matt-aitken** [comment]
@Kalmarv we have an option for specifying the environment filename. `npx @trigger.dev/cli@latest -e env.development`
