### ISSUE TITLE
[TRI-1795] Add $not to eventFilters

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#810]
EventFilters support lots of different nice matching, but they don't support `not`.

Add it to the schema:
https://github.com/triggerdotdev/trigger.dev/blob/main/packages/core/src/schemas/eventFilter.ts

Add the implementation:
https://github.com/triggerdotdev/trigger.dev/blob/main/packages/core/src/eventFilterMatches.ts

Add tests:
https://github.com/triggerdotdev/trigger.dev/blob/main/packages/core/test/eventFilterMatches.test.ts

<sub>[TRI-1795](https://linear.app/triggerdotdev/issue/TRI-1795/add-dollarnot-to-eventfilters)</sub>

**Comment by meetwithyash** [comment]
@matt-aitken , Please review my PR for adding $not to eventFilters.
