### ISSUE TITLE
[TRI-1797] Produce an ARM-compatible Docker image

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#817]
Currently our Docker image doesn't work on ARM, only x86.

<sub>[TRI-1797](https://linear.app/triggerdotdev/issue/TRI-1797/produce-an-arm-compatible-docker-image)</sub>

**Comment by adiologydev** [comment]
+1 really need this!

**Comment by adiologydev** [comment]
> "The v3 worker components don’t have ARM support yet." can this be fixed for v3?

+1 on this. I understand the product is cloud-first but this would be nice to have for the self-hosted community.

**Comment by devbaraus** [comment]
any news?
