### ISSUE TITLE
[TRI-1798] Events list – show all events that have been received

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#818]
An Events page, similar to the Runs page, that would show a paginated table with all events.

Info included for each event
- Event name
- Received time
- Delivery time (can be in the future)
- If it's been delivered yet
- Number of associated runs

You should be able to click through to view the event payload and then click through to any associated runs.

<sub>[TRI-1798](https://linear.app/triggerdotdev/issue/TRI-1798/events-list-show-all-events-that-have-been-received)</sub>

**Comment by Kritik-J** [comment]
@matt-aitken, Can you assign this to me?

**Comment by meetwithyash** [comment]
@Kritik-J , I already started working on this and notified about that in Discord. I have made the listings page. just the details page is remaining. I can push this and If you are okay, co-author that with me. You can go ahead and complete the details page.

<img width="1663" alt="image" src="https://github.com/triggerdotdev/trigger.dev/assets/32828966/bf0bce7c-3bea-4f5d-8356-bc43e953df3e">
