### ISSUE TITLE
Self-hosting migration fails if not using the default "public" schema

### ISSUE THREAD

**Issue by swag42dev** [triggerdotdev/trigger.dev#886]
https://github.com/triggerdotdev/trigger.dev/blob/336029b8428a826bfc92932a61653979a0e1fb79/apps/webapp/app/presenters/JobListPresenter.server.ts#L125

**Comment by swag42dev** [comment]
code: 'P2010',

clientVersion: '5.4.1',

meta: { code: '42P01', message: 'relation "public.JobRun" does not exist' }

}

**Comment by swag42dev** [comment]
and migration which fails if project hosted in custom schema eg "triggerdotdev"
CREATE INDEX idx_jobrun_jobId_createdAt ON "public"."JobRun" ("jobId", "createdAt" DESC);

**Comment by matt-aitken** [comment]
Good spot, a fix for this has been pushed to main. I'm creating another `latest` build right now, should be available in 10 mins to use.

**Comment by matt-aitken** [comment]
Ah shit I didn't spot the migration

**Comment by matt-aitken** [comment]
@swag42dev unfortunately it's not going to be easy to fix that migration. It's already been applied and just editing the file isn't an option as that causes an out-of-sync issue which would wipe everyone's databases when deploying.

There are complicated options Prisma offers but I'm not clear on the best approach at the moment.

I think you can manually resolve for yourself by doing this:

1. Run this on your database, it will mark that migration as done (even though it isn't):
```sh
prisma migrate resolve --applied "20240130165343_add_composite_index_to_job_run_for_job_id_and_created_at"
```
2. Manually perform the SQL migration to create the composite index:
```sql
CREATE INDEX idx_jobrun_jobId_createdAt ON "JobRun" ("jobId", "createdAt" DESC);
```

Sorry about this. That migration was auto-generated by Prisma when I used their @@index notation… 😠

**Comment by swag42dev** [comment]
@matt-aitken  no problem. i already fix migration. thank you for quick fix

**Comment by brentshulman-silkline** [comment]
This is and extremely annoying and causing issues with deploying on ECS that:
1. Make the docs incorrect
2. Means I need to deploy a separate db

**Comment by matt-aitken** [comment]
There's a more up to date issue on this with a better temporary fix: https://github.com/triggerdotdev/trigger.dev/issues/1026
